///////////////////////////////////////////////////////////////
//                 OMAP 4430 Control Registers
///////////////////////////////////////////////////////////////

//
// SYSCTRL_GENERAL_CORE Registers
//
#define CONTROL_GEN_CORE_REVISION               OMAP_R(0x4A002000)
#define CONTROL_GEN_CORE_HWINFO                 OMAP_R(0x4A002004)
#define CONTROL_GEN_CORE_SYSCONFIG              OMAP_R(0x4A002010)
#define CONTROL_STD_FUSE_DIE_ID_0               OMAP_R(0x4A002200)
#define CONTROL_ID_CODE                         OMAP_R(0x4A002204)
#define CONTROL_STD_FUSE_DIE_ID_1               OMAP_R(0x4A002208)
#define CONTROL_STD_FUSE_DIE_ID_2               OMAP_R(0x4A00220C)
#define CONTROL_STD_FUSE_DIE_ID_3               OMAP_R(0x4A002210)
#define CONTROL_STD_FUSE_PROD_ID_0              OMAP_R(0x4A002214)
#define CONTROL_STD_FUSE_PROD_ID_1              OMAP_R(0x4A002218)
#define CONTROL_STD_FUSE_USB_CONF               OMAP_R(0x4A00221C)
#define CONTROL_STD_FUSE_CONF                   OMAP_R(0x4A002220)
#define CONTROL_STD_FUSE_OPP_VDD_WKUP           OMAP_R(0x4A002228)
#define CONTROL_STD_FUSE_OPP_VDD_IVA_0          OMAP_R(0x4A00222C)
#define CONTROL_STD_FUSE_OPP_VDD_IVA_1          OMAP_R(0x4A002230)
#define CONTROL_STD_FUSE_OPP_VDD_IVA_2          OMAP_R(0x4A002234)
#define CONTROL_STD_FUSE_OPP_VDD_IVA_3          OMAP_R(0x4A002238)
#define CONTROL_STD_FUSE_OPP_VDD_MPU_0          OMAP_R(0x4A002240)
#define CONTROL_STD_FUSE_OPP_VDD_MPU_1          OMAP_R(0x4A002244)
#define CONTROL_STD_FUSE_OPP_VDD_MPU_2          OMAP_R(0x4A002248)
#define CONTROL_STD_FUSE_OPP_VDD_MPU_3          OMAP_R(0x4A00224C)
#define CONTROL_STD_FUSE_OPP_VDD_CORE_0         OMAP_R(0x4A002254)
#define CONTROL_STD_FUSE_OPP_VDD_CORE_1         OMAP_R(0x4A002258)
#define CONTROL_STD_FUSE_OPP_VDD_CORE_2         OMAP_R(0x4A00225C)
#define CONTROL_STD_FUSE_OPP_BGAP               OMAP_R(0x4A002260)
#define CONTROL_STD_FUSE_OPP_DPLL_0             OMAP_R(0x4A002264)
#define CONTROL_STD_FUSE_OPP_DPLL_1             OMAP_R(0x4A002268)
#define CONTROL_STATUS                          OMAP_R(0x4A0022C4)
#define CONTROL_SEC_ERR_STATUS_FUNC             OMAP_R(0x4A0022D0)
#define CONTROL_SEC_ERR_STATUS_DEBUG            OMAP_R(0x4A0022D4)
#define CONTROL_DEV_CONF                        OMAP_R(0x4A002300)
#define CONTROL_DSP_BOOTADDR                    OMAP_R(0x4A002304)
#define CONTROL_LDOVBB_IVA_VOLTAGE_CTRL         OMAP_R(0x4A002314)
#define CONTROL_LDOVBB_MPU_VOLTAGE_CTRL         OMAP_R(0x4A002318)
#define CONTROL_LDOSRAM_IVA_VOLTAGE_CTRL        OMAP_R(0x4A002320)
#define CONTROL_LDOSRAM_MPU_VOLTAGE_CTRL        OMAP_R(0x4A002324)
#define CONTROL_LDOSRAM_CORE_VOLTAGE_CTRL       OMAP_R(0x4A002328)
#define CONTROL_TEMP_SENSOR                     OMAP_R(0x4A00232C)
#define CONTROL_DPLL_NWELL_TRIM_0               OMAP_R(0x4A002330)
#define CONTROL_DPLL_NWELL_TRIM_1               OMAP_R(0x4A002334)
#define CONTROL_USBOTGHS_CONTROL                OMAP_R(0x4A00233C)
#define CONTROL_DSS_CONTROL                     OMAP_R(0x4A002340)
#define CONTROL_CORTEX_M3_MMUADDRTRANSLTR       OMAP_R(0x4A002348)
#define CONTROL_CORTEX_M3_MMUADDRLOGICTR        OMAP_R(0x4A00234C)
#define CONTROL_HWOBS_CONTROL                   OMAP_R(0x4A002350)
#define CONTROL_GEN_CORE_OCPREG_SPARE           OMAP_R(0x4A0023FC)
#define CONTROL_DEBOBS_FINAL_MUX_SEL            OMAP_R(0x4A002400)
#define CONTROL_DEBOBS_MMR_MPU                  OMAP_R(0x4A002408)
#define CONTROL_CONF_SDMA_REQ_SEL0              OMAP_R(0x4A00242C)
#define CONTROL_CONF_SDMA_REQ_SEL1              OMAP_R(0x4A002430)
#define CONTROL_CONF_SDMA_REQ_SEL2              OMAP_R(0x4A002434)
#define CONTROL_CONF_SDMA_REQ_SEL3              OMAP_R(0x4A002438)
#define CONTROL_CONF_CLK_SEL0                   OMAP_R(0x4A002440)
#define CONTROL_CONF_CLK_SEL1                   OMAP_R(0x4A002444)
#define CONTROL_CONF_CLK_SEL2                   OMAP_R(0x4A002448)
#define CONTROL_CONF_DPLL_FREQLOCK_SEL          OMAP_R(0x4A00244C)
#define CONTROL_CONF_DPLL_TINITZ_SEL            OMAP_R(0x4A002450)
#define CONTROL_CONF_DPLL_PHASELOCK_SEL         OMAP_R(0x4A002454)
#define CONTROL_CONF_DPLL_TENABLE_SEL           OMAP_R(0x4A00245C)
#define CONTROL_CONF_DPLL_TENABLEDIV_SEL        OMAP_R(0x4A002460)
#define CONTROL_CONF_DPLL_BYPASSACK_SEL         OMAP_R(0x4A002464)
#define CONTROL_CONF_DPLL_IDLE_SEL              OMAP_R(0x4A002468)
#define CONTROL_CORE_CONF_DEBUG_SEL_TST(i)      OMAP_R(0x4A002480+(i)*4)

//
// SYSCTRL_GENERAL_WKUP Registers
//
#define CONTROL_GEN_WKUP_REVISION                   OMAP_R(0x4A00C000)
#define CONTROL_GEN_WKUP_HWINFO                     OMAP_R(0x4A00C004)
#define CONTROL_GEN_WKUP_SYSCONFIG                  OMAP_R(0x4A00C010)
#define CONTROL_OCPREG_SPARE                        OMAP_R(0x4A00C10C)
#define CONTROL_WKUP_PROT_EMIF1_SDRAM_CONFIG_REG    OMAP_R(0x4A00C110)
#define CONTROL_WKUP_PROT_EMIF1_SDRAM_CONFIG2_REG   OMAP_R(0x4A00C114)
#define CONTROL_WKUP_PROT_EMIF2_SDRAM_CONFIG_REG    OMAP_R(0x4A00C118)
#define CONTROL_WKUP_PROT_EMIF2_SDRAM_CONFIG2_REG   OMAP_R(0x4A00C11C)
#define CONTROL_WKUP_CONF_DEBUG_SEL_TST(i)          OMAP_R(0x4A00C640+(i)*4)

//
// SYSCTRL_PADCONF_CORE Registers
//
#define CONTROL_PADCONF_CORE_REVISION                                   OMAP_R(0x4A100000)
#define CONTROL_PADCONF_CORE_HWINFO                                     OMAP_R(0x4A100004)
#define CONTROL_PADCONF_CORE_SYSCONFIG                                  OMAP_R(0x4A100010)
#define CONTROL_CORE_PAD0_GPMC_AD0_PAD1_GPMC_AD1                        OMAP_R(0x4A100040)
#define CONTROL_CORE_PAD0_GPMC_AD2_PAD1_GPMC_AD3                        OMAP_R(0x4A100044)
#define CONTROL_CORE_PAD0_GPMC_AD4_PAD1_GPMC_AD5                        OMAP_R(0x4A100048)
#define CONTROL_CORE_PAD0_GPMC_AD6_PAD1_GPMC_AD7                        OMAP_R(0x4A10004C)
#define CONTROL_CORE_PAD0_GPMC_AD8_PAD1_GPMC_AD9                        OMAP_R(0x4A100050)
#define CONTROL_CORE_PAD0_GPMC_AD10_PAD1_GPMC_AD11                      OMAP_R(0x4A100054)
#define CONTROL_CORE_PAD0_GPMC_AD12_PAD1_GPMC_AD13                      OMAP_R(0x4A100058)
#define CONTROL_CORE_PAD0_GPMC_AD14_PAD1_GPMC_AD15                      OMAP_R(0x4A10005C)
#define CONTROL_CORE_PAD0_GPMC_A16_PAD1_GPMC_A17                        OMAP_R(0x4A100060)
#define CONTROL_CORE_PAD0_GPMC_A18_PAD1_GPMC_A19                        OMAP_R(0x4A100064)
#define CONTROL_CORE_PAD0_GPMC_A20_PAD1_GPMC_A21                        OMAP_R(0x4A100068)
#define CONTROL_CORE_PAD0_GPMC_A22_PAD1_GPMC_A23                        OMAP_R(0x4A10006C)
#define CONTROL_CORE_PAD0_GPMC_A24_PAD1_GPMC_A25                        OMAP_R(0x4A100070)
#define CONTROL_CORE_PAD0_GPMC_NCS0_PAD1_GPMC_NCS1                      OMAP_R(0x4A100074)
#define CONTROL_CORE_PAD0_GPMC_NCS2_PAD1_GPMC_NCS3                      OMAP_R(0x4A100078)
#define CONTROL_CORE_PAD0_GPMC_NWP_PAD1_GPMC_CLK                        OMAP_R(0x4A10007C)
#define CONTROL_CORE_PAD0_GPMC_NADV_ALE_PAD1_GPMC_NOE                   OMAP_R(0x4A100080)
#define CONTROL_CORE_PAD0_GPMC_NWE_PAD1_GPMC_NBE0_CLE                   OMAP_R(0x4A100084)
#define CONTROL_CORE_PAD0_GPMC_NBE1_PAD1_GPMC_WAIT0                     OMAP_R(0x4A100088)
#define CONTROL_CORE_PAD0_GPMC_WAIT1_PAD1_GPMC_WAIT2                    OMAP_R(0x4A10008C)
#define CONTROL_CORE_PAD0_GPMC_NCS4_PAD1_GPMC_NCS5                      OMAP_R(0x4A100090)
#define CONTROL_CORE_PAD0_GPMC_NCS6_PAD1_GPMC_NCS7                      OMAP_R(0x4A100094)
#define CONTROL_CORE_PAD0_GPIO63_PAD1_GPIO64                            OMAP_R(0x4A100098)
#define CONTROL_CORE_PAD0_GPIO65_PAD1_GPIO66                            OMAP_R(0x4A10009C)
#define CONTROL_CORE_PAD0_CSI21_DX0_PAD1_CSI21_DY0                      OMAP_R(0x4A1000A0)
#define CONTROL_CORE_PAD0_CSI21_DX1_PAD1_CSI21_DY1                      OMAP_R(0x4A1000A4)
#define CONTROL_CORE_PAD0_CSI21_DX2_PAD1_CSI21_DY2                      OMAP_R(0x4A1000A8)
#define CONTROL_CORE_PAD0_CSI21_DX3_PAD1_CSI21_DY3                      OMAP_R(0x4A1000AC)
#define CONTROL_CORE_PAD0_CSI21_DX4_PAD1_CSI21_DY4                      OMAP_R(0x4A1000B0)
#define CONTROL_CORE_PAD0_CSI22_DX0_PAD1_CSI22_DY0                      OMAP_R(0x4A1000B4)
#define CONTROL_CORE_PAD0_CSI22_DX1_PAD1_CSI22_DY1                      OMAP_R(0x4A1000B8)
#define CONTROL_CORE_PAD0_CAM_SHUTTER_PAD1_CAM_STROBE                   OMAP_R(0x4A1000BC)
#define CONTROL_CORE_PAD0_CAM_GLOBALRESET_PAD1_USBB1_ULPITLL_CLK        OMAP_R(0x4A1000C0)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_STP_PAD1_USBB1_ULPITLL_DIR      OMAP_R(0x4A1000C4)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_NXT_PAD1_USBB1_ULPITLL_DAT0     OMAP_R(0x4A1000C8)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_DAT1_PAD1_USBB1_ULPITLL_DAT2    OMAP_R(0x4A1000CC)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_DAT3_PAD1_USBB1_ULPITLL_DAT4    OMAP_R(0x4A1000D0)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_DAT5_PAD1_USBB1_ULPITLL_DAT6    OMAP_R(0x4A1000D4)
#define CONTROL_CORE_PAD0_USBB1_ULPITLL_DAT7_PAD1_USBB1_HSIC_DATA       OMAP_R(0x4A1000D8)
#define CONTROL_CORE_PAD0_USBB1_HSIC_STROBE_PAD1_USBC1_ICUSB_DP         OMAP_R(0x4A1000DC)
#define CONTROL_CORE_PAD0_USBC1_ICUSB_DM_PAD1_SDMMC1_CLK                OMAP_R(0x4A1000E0)
#define CONTROL_CORE_PAD0_SDMMC1_CMD_PAD1_SDMMC1_DAT0                   OMAP_R(0x4A1000E4)
#define CONTROL_CORE_PAD0_SDMMC1_DAT1_PAD1_SDMMC1_DAT2                  OMAP_R(0x4A1000E8)
#define CONTROL_CORE_PAD0_SDMMC1_DAT3_PAD1_SDMMC1_DAT4                  OMAP_R(0x4A1000EC)
#define CONTROL_CORE_PAD0_SDMMC1_DAT5_PAD1_SDMMC1_DAT6                  OMAP_R(0x4A1000F0)
#define CONTROL_CORE_PAD0_SDMMC1_DAT7_PAD1_ABE_MCBSP2_CLKX              OMAP_R(0x4A1000F4)
#define CONTROL_CORE_PAD0_ABE_MCBSP2_DR_PAD1_ABE_MCBSP2_DX              OMAP_R(0x4A1000F8)
#define CONTROL_CORE_PAD0_ABE_MCBSP2_FSX_PAD1_ABE_MCBSP1_CLKX           OMAP_R(0x4A1000FC)
#define CONTROL_CORE_PAD0_ABE_MCBSP1_DR_PAD1_ABE_MCBSP1_DX              OMAP_R(0x4A100100)
#define CONTROL_CORE_PAD0_ABE_MCBSP1_FSX_PAD1_ABE_PDM_UL_DATA           OMAP_R(0x4A100104)
#define CONTROL_CORE_PAD0_ABE_PDM_DL_DATA_PAD1_ABE_PDM_FRAME            OMAP_R(0x4A100108)
#define CONTROL_CORE_PAD0_ABE_PDM_LB_CLK_PAD1_ABE_CLKS                  OMAP_R(0x4A10010C)
#define CONTROL_CORE_PAD0_ABE_DMIC_CLK1_PAD1_ABE_DMIC_DIN1              OMAP_R(0x4A100110)
#define CONTROL_CORE_PAD0_ABE_DMIC_DIN2_PAD1_ABE_DMIC_DIN3              OMAP_R(0x4A100114)
#define CONTROL_CORE_PAD0_UART2_CTS_PAD1_UART2_RTS                      OMAP_R(0x4A100118)
#define CONTROL_CORE_PAD0_UART2_RX_PAD1_UART2_TX                        OMAP_R(0x4A10011C)
#define CONTROL_CORE_PAD0_HDQ_SIO_PAD1_I2C1_SCL                         OMAP_R(0x4A100120)
#define CONTROL_CORE_PAD0_I2C1_SDA_PAD1_I2C2_SCL                        OMAP_R(0x4A100124)
#define CONTROL_CORE_PAD0_I2C2_SDA_PAD1_I2C3_SCL                        OMAP_R(0x4A100128)
#define CONTROL_CORE_PAD0_I2C3_SDA_PAD1_I2C4_SCL                        OMAP_R(0x4A10012C)
#define CONTROL_CORE_PAD0_I2C4_SDA_PAD1_MCSPI1_CLK                      OMAP_R(0x4A100130)
#define CONTROL_CORE_PAD0_MCSPI1_SOMI_PAD1_MCSPI1_SIMO                  OMAP_R(0x4A100134)
#define CONTROL_CORE_PAD0_MCSPI1_CS0_PAD1_MCSPI1_CS1                    OMAP_R(0x4A100138)
#define CONTROL_CORE_PAD0_MCSPI1_CS2_PAD1_MCSPI1_CS3                    OMAP_R(0x4A10013C)
#define CONTROL_CORE_PAD0_UART3_CTS_RCTX_PAD1_UART3_RTS_SD              OMAP_R(0x4A100140)
#define CONTROL_CORE_PAD0_UART3_RX_IRRX_PAD1_UART3_TX_IRTX              OMAP_R(0x4A100144)
#define CONTROL_CORE_PAD0_SDMMC5_CLK_PAD1_SDMMC5_CMD                    OMAP_R(0x4A100148)
#define CONTROL_CORE_PAD0_SDMMC5_DAT0_PAD1_SDMMC5_DAT1                  OMAP_R(0x4A10014C)
#define CONTROL_CORE_PAD0_SDMMC5_DAT2_PAD1_SDMMC5_DAT3                  OMAP_R(0x4A100150)
#define CONTROL_CORE_PAD0_MCSPI4_CLK_PAD1_MCSPI4_SIMO                   OMAP_R(0x4A100154)
#define CONTROL_CORE_PAD0_MCSPI4_SOMI_PAD1_MCSPI4_CS0                   OMAP_R(0x4A100158)
#define CONTROL_CORE_PAD0_UART4_RX_PAD1_UART4_TX                        OMAP_R(0x4A10015C)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_CLK_PAD1_USBB2_ULPITLL_STP      OMAP_R(0x4A100160)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_DIR_PAD1_USBB2_ULPITLL_NXT      OMAP_R(0x4A100164)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_DAT0_PAD1_USBB2_ULPITLL_DAT1    OMAP_R(0x4A100168)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_DAT2_PAD1_USBB2_ULPITLL_DAT3    OMAP_R(0x4A10016C)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_DAT4_PAD1_USBB2_ULPITLL_DAT5    OMAP_R(0x4A100170)
#define CONTROL_CORE_PAD0_USBB2_ULPITLL_DAT6_PAD1_USBB2_ULPITLL_DAT7    OMAP_R(0x4A100174)
#define CONTROL_CORE_PAD0_USBB2_HSIC_DATA_PAD1_USBB2_HSIC_STROBE        OMAP_R(0x4A100178)
#define CONTROL_CORE_PAD0_KPD_COL3_PAD1_KPD_COL4                        OMAP_R(0x4A10017C)
#define CONTROL_CORE_PAD0_KPD_COL5_PAD1_KPD_COL0                        OMAP_R(0x4A100180)
#define CONTROL_CORE_PAD0_KPD_COL1_PAD1_KPD_COL2                        OMAP_R(0x4A100184)
#define CONTROL_CORE_PAD0_KPD_ROW3_PAD1_KPD_ROW4                        OMAP_R(0x4A100188)
#define CONTROL_CORE_PAD0_KPD_ROW5_PAD1_KPD_ROW0                        OMAP_R(0x4A10018C)
#define CONTROL_CORE_PAD0_KPD_ROW1_PAD1_KPD_ROW2                        OMAP_R(0x4A100190)
#define CONTROL_CORE_PAD0_USBA0_OTG_CE_PAD1_USBA0_OTG_DP                OMAP_R(0x4A100194)
#define CONTROL_CORE_PAD0_USBA0_OTG_DM_PAD1_FREF_CLK1_OUT               OMAP_R(0x4A100198)
#define CONTROL_CORE_PAD0_FREF_CLK2_OUT_PAD1_SYS_NIRQ1                  OMAP_R(0x4A10019C)
#define CONTROL_CORE_PAD0_SYS_NIRQ2_PAD1_SYS_BOOT0                      OMAP_R(0x4A1001A0)
#define CONTROL_CORE_PAD0_SYS_BOOT1_PAD1_SYS_BOOT2                      OMAP_R(0x4A1001A4)
#define CONTROL_CORE_PAD0_SYS_BOOT3_PAD1_SYS_BOOT4                      OMAP_R(0x4A1001A8)
#define CONTROL_CORE_PAD0_SYS_BOOT5_PAD1_DPM_EMU0                       OMAP_R(0x4A1001AC)
#define CONTROL_CORE_PAD0_DPM_EMU1_PAD1_DPM_EMU2                        OMAP_R(0x4A1001B0)
#define CONTROL_CORE_PAD0_DPM_EMU3_PAD1_DPM_EMU4                        OMAP_R(0x4A1001B4)
#define CONTROL_CORE_PAD0_DPM_EMU5_PAD1_DPM_EMU6                        OMAP_R(0x4A1001B8)
#define CONTROL_CORE_PAD0_DPM_EMU7_PAD1_DPM_EMU8                        OMAP_R(0x4A1001BC)
#define CONTROL_CORE_PAD0_DPM_EMU9_PAD1_DPM_EMU10                       OMAP_R(0x4A1001C0)
#define CONTROL_CORE_PAD0_DPM_EMU11_PAD1_DPM_EMU12                      OMAP_R(0x4A1001C4)
#define CONTROL_CORE_PAD0_DPM_EMU13_PAD1_DPM_EMU14                      OMAP_R(0x4A1001C8)
#define CONTROL_CORE_PAD0_DPM_EMU15_PAD1_DPM_EMU16                      OMAP_R(0x4A1001CC)
#define CONTROL_CORE_PAD0_DPM_EMU17_PAD1_DPM_EMU18                      OMAP_R(0x4A1001D0)
#define CONTROL_CORE_PAD0_DPM_EMU19                                     OMAP_R(0x4A1001D4)
#define CONTROL_PADCONF_WAKEUPEVENT_0                                   OMAP_R(0x4A1001D8)
#define CONTROL_PADCONF_WAKEUPEVENT_1                                   OMAP_R(0x4A1001DC)
#define CONTROL_PADCONF_WAKEUPEVENT_2                                   OMAP_R(0x4A1001E0)
#define CONTROL_PADCONF_WAKEUPEVENT_3                                   OMAP_R(0x4A1001E4)
#define CONTROL_PADCONF_WAKEUPEVENT_4                                   OMAP_R(0x4A1001E8)
#define CONTROL_PADCONF_WAKEUPEVENT_5                                   OMAP_R(0x4A1001EC)
#define CONTROL_PADCONF_WAKEUPEVENT_6                                   OMAP_R(0x4A1001F0)
#define CONTROL_PADCONF_GLOBAL                                          OMAP_R(0x4A1005A0)
#define CONTROL_CORE_PADCONF_MODE                                       OMAP_R(0x4A1005A4)
#define CONTROL_SMART1IO_PADCONF_0                                      OMAP_R(0x4A1005A8)
#define CONTROL_SMART1IO_PADCONF_1                                      OMAP_R(0x4A1005AC)
#define CONTROL_SMART2IO_PADCONF_0                                      OMAP_R(0x4A1005B0)
#define CONTROL_SMART2IO_PADCONF_1                                      OMAP_R(0x4A1005B4)
#define CONTROL_SMART3IO_PADCONF_0                                      OMAP_R(0x4A1005B8)
#define CONTROL_SMART3IO_PADCONF_1                                      OMAP_R(0x4A1005BC)
#define CONTROL_SMART3IO_PADCONF_2                                      OMAP_R(0x4A1005C0)
#define CONTROL_USBB_HSIC                                               OMAP_R(0x4A1005C4)
#define CONTROL_SMART3IO_PADCONF_3                                      OMAP_R(0x4A1005C8)
#define CONTROL_SMART2IO_PADCONF_2                                      OMAP_R(0x4A1005CC)
#define CONTROL_SMART1IO_PADCONF_2                                      OMAP_R(0x4A1005D0)
#define CONTROL_SMART1IO_PADCONF_3                                      OMAP_R(0x4A1005D4)
#define CONTROL_C2CIO_PADCONF_0                                         OMAP_R(0x4A1005D8)
#define CONTROL_PBIASLITE                                               OMAP_R(0x4A100600)
#define CONTROL_I2C_0                                                   OMAP_R(0x4A100604)
#define CONTROL_CAMERA_RX                                               OMAP_R(0x4A100608)
#define CONTROL_AVDAC                                                   OMAP_R(0x4A10060C)
#define CONTROL_MMC2                                                    OMAP_R(0x4A100614)
#define CONTROL_DSIPHY                                                  OMAP_R(0x4A100618)
#define CONTROL_MCBSPLP                                                 OMAP_R(0x4A10061C)
#define CONTROL_USB2PHYCORE                                             OMAP_R(0x4A100620)
#define CONTROL_I2C_1                                                   OMAP_R(0x4A100624)
#define CONTROL_MMC1                                                    OMAP_R(0x4A100628)
#define CONTROL_HSI                                                     OMAP_R(0x4A10062C)
#define CONTROL_USB                                                     OMAP_R(0x4A100630)
#define CONTROL_HDQ                                                     OMAP_R(0x4A100634)
#define CONTROL_LPDDR2IO1_0                                             OMAP_R(0x4A100638)
#define CONTROL_LPDDR2IO1_1                                             OMAP_R(0x4A10063C)
#define CONTROL_LPDDR2IO1_2                                             OMAP_R(0x4A100640)
#define CONTROL_LPDDR2IO1_3                                             OMAP_R(0x4A100644)
#define CONTROL_LPDDR2IO2_0                                             OMAP_R(0x4A100648)
#define CONTROL_LPDDR2IO2_1                                             OMAP_R(0x4A10064C)
#define CONTROL_LPDDR2IO2_2                                             OMAP_R(0x4A100650)
#define CONTROL_LPDDR2IO2_3                                             OMAP_R(0x4A100654)
#define CONTROL_BUS_HOLD                                                OMAP_R(0x4A100658)
#define CONTROL_C2C                                                     OMAP_R(0x4A10065C)
#define CONTROL_CORE_CONTROL_SPARE_RW                                   OMAP_R(0x4A100660)
#define CONTROL_CORE_CONTROL_SPARE_R                                    OMAP_R(0x4A100664)
#define CONTROL_CORE_CONTROL_SPARE_R_C0                                 OMAP_R(0x4A100668)
#define CONTROL_CORE_CONTROL_SPARE_RW1                                  OMAP_R(0x4A10066C)
#define CONTROL_CORE_CONTROL_SPARE_RW2                                  OMAP_R(0x4A100670)
#define CONTROL_CORE_CONTROL_SPARE_RW3                                  OMAP_R(0x4A100674)
#define CONTROL_CORE_CONTROL_SPARE_RW4                                  OMAP_R(0x4A100678)
#define CONTROL_CORE_CONTROL_SPARE_RW5                                  OMAP_R(0x4A10067C)
#define CONTROL_CORE_CONTROL_SPARE_RW6                                  OMAP_R(0x4A100680)
#define CONTROL_CORE_CONTROL_SPARE_RW7                                  OMAP_R(0x4A100684)
#define CONTROL_CORE_CONTROL_SPARE_RW8                                  OMAP_R(0x4A100688)
#define CONTROL_CORE_CONTROL_SPARE_RW9                                  OMAP_R(0x4A10068C)
#define CONTROL_CORE_CONTROL_SPARE_R1                                   OMAP_R(0x4A100690)
#define CONTROL_EFUSE_1                                                 OMAP_R(0x4A100700)
#define CONTROL_EFUSE_2                                                 OMAP_R(0x4A100704)
#define CONTROL_EFUSE_3                                                 OMAP_R(0x4A100708)
#define CONTROL_EFUSE_4                                                 OMAP_R(0x4A10070C)

//
// SYSCTRL_PADCONF_WKUP Registers
//
#define CONTROL_PADCONF_WKUP_REVISION                               OMAP_R(0x4A31E000)
#define CONTROL_PADCONF_WKUP_HWINFO                                 OMAP_R(0x4A31E004)
#define CONTROL_PADCONF_WKUP_SYSCONFIG                              OMAP_R(0x4A31E010)
#define CONTROL_WKUP_PAD0_GPIO_WK0_PAD1_GPIO_WK1                    OMAP_R(0x4A31E040)
#define CONTROL_WKUP_PAD0_GPIO_WK2_PAD1_GPIO_WK3                    OMAP_R(0x4A31E044)
#define CONTROL_WKUP_PAD0_GPIO_WK4_PAD1_SR_SCL                      OMAP_R(0x4A31E048)
#define CONTROL_WKUP_PAD0_SR_SDA_PAD1_FREF_XTAL_IN                  OMAP_R(0x4A31E04C)
#define CONTROL_WKUP_PAD0_FREF_SLICER_IN_PAD1_FREF_CLK_IOREQ        OMAP_R(0x4A31E050)
#define CONTROL_WKUP_PAD0_FREF_CLK0_OUT_PAD1_FREF_CLK3_REQ          OMAP_R(0x4A31E054)
#define CONTROL_WKUP_PAD0_FREF_CLK3_OUT_PAD1_FREF_CLK4_REQ          OMAP_R(0x4A31E058)
#define CONTROL_WKUP_PAD0_FREF_CLK4_OUT_PAD1_SYS_32K                OMAP_R(0x4A31E05C)
#define CONTROL_WKUP_PAD0_SYS_NRESPWRON_PAD1_SYS_NRESWARM           OMAP_R(0x4A31E060)
#define CONTROL_WKUP_PAD0_SYS_PWR_REQ_PAD1_SYS_PWRON_RESET_OUT      OMAP_R(0x4A31E064)
#define CONTROL_WKUP_PAD0_SYS_BOOT6_PAD1_SYS_BOOT7                  OMAP_R(0x4A31E068)
#define CONTROL_WKUP_PAD0_JTAG_NTRST_PAD1_JTAG_TCK                  OMAP_R(0x4A31E06C)
#define CONTROL_WKUP_PAD0_JTAG_RTCK_PAD1_JTAG_TMS_TMSC              OMAP_R(0x4A31E070)
#define CONTROL_WKUP_PAD0_JTAG_TDI_PAD1_JTAG_TDO                    OMAP_R(0x4A31E074)
#define CONTROL_WKUP_PADCONF_WAKEUPEVENT_0                          OMAP_R(0x4A31E07C)
#define CONTROL_SMART1NOPMIO_PADCONF_0                              OMAP_R(0x4A31E5A0)
#define CONTROL_SMART1NOPMIO_PADCONF_1                              OMAP_R(0x4A31E5A4)
#define CONTROL_WKUP_PADCONF_MODE                                   OMAP_R(0x4A31E5A8)
#define CONTROL_XTAL_OSCILLATOR                                     OMAP_R(0x4A31E5AC)
#define CONTROL_SMART3NOPMIO_PADCONF_0                              OMAP_R(0x4A31E5B0)
#define CONTROL_SMART3NOPMIO_PADCONF_1                              OMAP_R(0x4A31E5B4)
#define CONTROL_GPIOWK                                              OMAP_R(0x4A31E600)
#define CONTROL_I2C_2                                               OMAP_R(0x4A31E604)
#define CONTROL_JTAG                                                OMAP_R(0x4A31E608)
#define CONTROL_SYS                                                 OMAP_R(0x4A31E60C)
#define CONTROL_WKUP_CONTROL_SPARE_RW                               OMAP_R(0x4A31E614)
#define CONTROL_WKUP_CONTROL_SPARE_R                                OMAP_R(0x4A31E618)
#define CONTROL_WKUP_CONTROL_SPARE_R_C0                             OMAP_R(0x4A31E61C)
#define CONTROL_WKUP_CONTROL_SPARE_RW1                              OMAP_R(0x4A31E620)
#define CONTROL_WKUP_CONTROL_SPARE_RW2                              OMAP_R(0x4A31E624)
#define CONTROL_WKUP_CONTROL_SPARE_RW3                              OMAP_R(0x4A31E628)
#define CONTROL_WKUP_CONTROL_SPARE_RW4                              OMAP_R(0x4A31E62C)
#define CONTROL_WKUP_CONTROL_SPARE_RW5                              OMAP_R(0x4A31E630)
#define CONTROL_WKUP_CONTROL_SPARE_RW6                              OMAP_R(0x4A31E634)
#define CONTROL_WKUP_CONTROL_SPARE_RW7                              OMAP_R(0x4A31E638)
#define CONTROL_WKUP_CONTROL_SPARE_RW8                              OMAP_R(0x4A31E63C)
#define CONTROL_WKUP_CONTROL_SPARE_RW9                              OMAP_R(0x4A31E640)
#define CONTROL_WKUP_CONTROL_SPARE_R1                               OMAP_R(0x4A31E64C)

////////////////////////////////////////////////////////////////////
// Bit Fields
////////////////////////////////////////////////////////////////////
// 
// !!! PLEASE NOTE
// that not all flags are applicable to all registers! Refer to
// datasheet.
//
// Registers with only one field starting from bit 0 are
// often left undescribed.
//
// In most cases names of fields are given the same as in the 
// datasheet. But in some cases they are
// 1) generalized for several registers in order to shorten 
//    the description (and this file also).
// 2) mangled in order to solve name conflicts because a few fields
//    are named identically in the datasheet.
//

//
// FUSE and identification registers are skipped!
// 

// CONTROL_*_SYSCONFIG
#define IP_SYSCONFIG_IDLEMODE(x)    (((x) & 0x3) << 2)

// CONTROL_SEC_ERR_STATUS_DEBUG
#define L3RAM_DBGFW_ERROR           (1 << 1)
#define GPMC_DBGFW_ERROR            (1 << 2)
#define EMIF_DBGFW_ERROR            (1 << 3)
#define IVAHD_DBGFW_ERROR           (1 << 4)
#define DUAL_CORTEX_M3_DBGFW_ERROR  (1 << 5)
#define SL2_DBGFW_ERROR             (1 << 6)
#define C2C_DBGFW_ERROR             (1 << 12)
#define SGX_DBGFW_ERROR             (1 << 13)
#define DSS_DBGFW_ERROR             (1 << 14)
#define ISS_DBGFW_ERROR             (1 << 15)
#define L4_PERIPH_DBGFW_ERROR       (1 << 16)
#define L4_CONFIG_DBGFW_ERROR       (1 << 17)
#define DEBUGSS_DBGFW_ERROR         (1 << 18)
#define L4_AUDIOBE_DBGFW_ERROR      (1 << 19)
#define C2C_INIT_DBGFW_ERROR        (1 << 20)

// CONTROL_DEV_CONF
#define USBPHY_PD                   (1 << 0)

// CONTROL_DSP_BOOTADDR
#define DSP_BOOT_LOAD_ADDR(x)       (((x) & 0x3FFFFF) << 10)

// CONTROL_LDOVBB_IVA_VOLTAGE_CTRL
#define LDOVBBIVA_FBB_VSET_OUT      ((x) & 0x1F)
#define LDOVBBIVA_FBB_VSET_IN       (((x) & 0x1F) << 5)
#define LDOVBBIVA_FBB_MUX_CTRL      (1 << 10)

// CONTROL_LDOVBB_MPU_VOLTAGE_CTRL
#define LDOVBBMPU_FBB_VSET_OUT      ((x) & 0x1F)
#define LDOVBBMPU_FBB_VSET_IN       (((x) & 0x1F) << 5)
#define LDOVBBMPU_FBB_MUX_CTRL      (1 << 10)

// CONTROL_LDOSRAM_IVA_VOLTAGE_CTRL
#define LDOSRAMIVA_ACTMODE_VSET_OUT(x)      ((x) & 0x1F)
#define LDOSRAMIVA_ACTMODE_VSET_IN(x)       (((x) & 0x1F) << 5)
#define LDOSRAMIVA_ACTMODE_MUX_CTRL         (1 << 10)
#define LDOSRAMIVA_RETMODE_VSET_OUT(x)      (((x) & 0x1F) << 16)
#define LDOSRAMIVA_RETMODE_VSET_IN(x)       (((x) & 0x1F) << 21)
#define LDOSRAMIVA_RETMODE_MUX_CTRL         (1 << 26)

// CONTROL_LDOSRAM_MPU_VOLTAGE_CTRL
#define LDOSRAMMPU_ACTMODE_VSET_OUT(x)      ((x) & 0x1F)
#define LDOSRAMMPU_ACTMODE_VSET_IN(x)       (((x) & 0x1F) << 5)
#define LDOSRAMMPU_ACTMODE_MUX_CTRL         (1 << 10)
#define LDOSRAMMPU_RETMODE_VSET_OUT(x)      (((x) & 0x1F) << 16)
#define LDOSRAMMPU_RETMODE_VSET_IN(x)       (((x) & 0x1F) << 21)
#define LDOSRAMMPU_RETMODE_MUX_CTRL         (1 << 26)

// CONTROL_LDOSRAM_CORE_VOLTAGE_CTRL
#define LDOSRAMCORE_ACTMODE_VSET_OUT(x)      ((x) & 0x1F)
#define LDOSRAMCORE_ACTMODE_VSET_IN(x)       (((x) & 0x1F) << 5)
#define LDOSRAMCORE_ACTMODE_MUX_CTRL         (1 << 10)
#define LDOSRAMCORE_RETMODE_VSET_OUT(x)      (((x) & 0x1F) << 16)
#define LDOSRAMCORE_RETMODE_VSET_IN(x)       (((x) & 0x1F) << 21)
#define LDOSRAMCORE_RETMODE_MUX_CTRL         (1 << 26)

// CONTROL_TEMP_SENSOR
#define BGAP_TEMP_SENSOR_DTEMP(x)           ((x) & 0xFF)
#define BGAP_TEMP_SENSOR_EOCZ               (1 << 8)
#define BGAP_TEMP_SENSOR_SOC                (1 << 9)
#define BGAP_TEMP_SENSOR_CONTCONV           (1 << 10)
#define BGAP_TSHUT                          (1 << 11)
#define BGAP_TEMPSOFF                       (1 << 12)

// CONTROL_DPLL_NWELL_TRIM_0
#define DPLL_MPU_NWELL_TRIM(x)              ((x) & 0x1F)
#define DPLL_MPU_NWELL_TRIM_MUX_CTRL        (1 << 5)
#define DPLL_IVA_NWELL_TRIM(x)              (((x) & 0x1F) << 6)
#define DPLL_IVA_NWELL_TRIM_MUX_CTRL        (1 << 11)
#define DPLL_CORE_NWELL_TRIM(x)             (((x) & 0x1F) << 12)
#define DPLL_CORE_NWELL_TRIM_MUX_CTRL       (1 << 17)
#define DPLL_PER_NWELL_TRIM(x)              (((x) & 0x1F) << 18)
#define DPLL_PER_NWELL_TRIM_MUX_CTRL        (1 << 23)
#define DPLL_ABE_NWELL_TRIM(x)              (((x) & 0x1F) << 24)
#define DPLL_ABE_NWELL_TRIM_MUX_CTRL        (1 << 29)

// CONTROL_DPLL_NWELL_TRIM_1
#define DPLL_DSI1_NWELL_TRIM(x)             ((x) & 0x1F)
#define DPLL_DSI1_NWELL_TRIM_MUX_CTRL       (1 << 5)
#define DPLL_DSI2_NWELL_TRIM(x)             (((x) & 0x1F) << 6)
#define DPLL_DSI2_NWELL_TRIM_MUX_CTRL       (1 << 11)
#define DPLL_USB_NWELL_TRIM(x)              (((x) & 0x1F) << 18)
#define DPLL_USB_NWELL_TRIM_MUX_CTRL        (1 << 23)

// CONTROL_USBOTGHS_CONTROL
#define AVALID                              (1 << 0)
#define BVALID                              (1 << 1)
#define VBUSVALID                           (1 << 2)
#define SESSEND                             (1 << 3)
#define IDDIG                               (1 << 4)
#define IDPULLUP                            (1 << 5)
#define DRVVBUS                             (1 << 6)
#define CHRGVBUS                            (1 << 7)
#define DISCHRGVBUS                         (1 << 8)

// CONTROL_DSS_CONTROL
#define DSS_MUX6_SELECT                     (1 << 0)

// CONTROL_CORTEX_M3_MMUADDRTRANSLTR
#define CORTEX_M3_MMUADDRTRANSLTR(x)        ((x) & 0xFFFFF)

// CONTROL_CORTEX_M3_MMUADDRLOGICTR
#define CORTEX_M3_MMUADDRLOGICTR(x)         ((x) & 0xFFFFF)

// CONTROL_HWOBS_CONTROL
#define HWOBS_MACRO_ENABLE                  (1 << 0)
#define HWOBS_ALL_ONE_MODE                  (1 << 1)
#define HWOBS_ALL_ZERO_MODE                 (1 << 2)
#define HWOBS_CLKDIV_SEL(x)                 (((x) & 0x1F) << 3)

// CONTROL_GEN_CORE_OCPREG_SPARE
// CONTROL_OCPREG_SPARE
#define OCPREG_SPARE(n)                     (1 << (n))

// CONTROL_WKUP_PROT_EMIF1_SDRAM_CONFIG_REG
// CONTROL_WKUP_PROT_EMIF2_SDRAM_CONFIG_REG
#define EMIF_SDRAM_PAGESIZE(x)             ((x) & 0x7)
#define EMIF_SDRAM_EBANK                   (1 << 3)
#define EMIF_SDRAM_IBANK(x)                (((x) & 0x7) << 4)
#define EMIF_SDRAM_ROWSIZE(x)              (((x) & 0x7) << 7)
#define EMIF_SDRAM_CL(x)                   (((x) & 0xF) << 10)
#define EMIF_SDRAM_NARROW_MODE(x)          (((x) & 0x3) << 14)
#define EMIF_SDRAM_DDR_DISABLE_DLL         (1 << 20)
#define EMIF_SDRAM_DDR2_DDQS               (1 << 23)
#define EMIF_SDRAM_IBANK_POS(x)            (((x) & 0x3) << 27)
#define EMIF_SDRAM_TYPE(x)                 (((x) & 0x7) << 29)

// CONTROL_WKUP_PROT_EMIF1_SDRAM_CONFIG2_REG
// CONTROL_WKUP_PROT_EMIF2_SDRAM_CONFIG2_REG
#define EMIF_SDRAM_RDBSIZE(x)              ((x) & 0x7)
#define EMIF_SDRAM_RDBNUM(x)               (((x) & 0x3) << 4)
#define EMIF_SDRAM_CS1NVMEN                (1 << 30)

// Bit map for pad configuration registers. Fields with suffix 1
// are dedicated to first pad in the name of a register, with suffix 2 -
// to the second pad. 
// For example, register CONTROL_CORE_PAD0_GPIO63_PAD1_GPIO64,
// as it can be seen from the name of register, controls pads PAD0_GPIO63 
// and PAD1_GPIO64. Fields MUXMODE1, PULLUDENABLE1, ..., WAKEUPEVENT1
// configure PAD0_GPIO63 and MUXMODE2, PULLUDENABLE2, ..., WAKEUPEVENT2
// configure PAD1_GPIO64.
#define MUXMODE1(x)                             ((x) & 0x7)
#define PULLUDENABLE1                           (1 << 3)
#define PULLTYPESELECT1                         (1 << 4)
#define INPUTENABLE1                            (1 << 8)
#define OFFMODEENABLE1                          (1 << 9)
#define OFFMODEOUTENABLE1                       (1 << 10)
#define OFFMODEOUTVALUE1                        (1 << 11)
#define OFFMODEPULLUDENABLE1                    (1 << 12)
#define OFFMODEPULLTYPESELECT1                  (1 << 13)
#define WAKEUPENABLE1                           (1 << 14)
#define WAKEUPEVENT1                            (1 << 15)
#define MUXMODE2(x)                             (((x) & 0x7) << 16)
#define PULLUDENABLE2                           (1 << 19)
#define PULLTYPESELECT2                         (1 << 20)
#define INPUTENABLE2                            (1 << 24)
#define OFFMODEENABLE2                          (1 << 25)
#define OFFMODEOUTENABLE2                       (1 << 26)
#define OFFMODEOUTVALUE2                        (1 << 27)
#define OFFMODEPULLUDENABLE2                    (1 << 28)
#define OFFMODEPULLTYPESELECT2                  (1 << 29)
#define WAKEUPENABLE2                           (1 << 30)
#define WAKEUPEVENT2                            (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_0
#define GPMC_AD0_DUPLICATEWAKEUPEVENT           (1 << 0)
#define GPMC_AD1_DUPLICATEWAKEUPEVENT           (1 << 1)
#define GPMC_AD2_DUPLICATEWAKEUPEVENT           (1 << 2)
#define GPMC_AD3_DUPLICATEWAKEUPEVENT           (1 << 3)
#define GPMC_AD4_DUPLICATEWAKEUPEVENT           (1 << 4)
#define GPMC_AD5_DUPLICATEWAKEUPEVENT           (1 << 5)
#define GPMC_AD6_DUPLICATEWAKEUPEVENT           (1 << 6)
#define GPMC_AD7_DUPLICATEWAKEUPEVENT           (1 << 7)
#define GPMC_AD8_DUPLICATEWAKEUPEVENT           (1 << 8)
#define GPMC_AD9_DUPLICATEWAKEUPEVENT           (1 << 9)
#define GPMC_AD10_DUPLICATEWAKEUPEVENT          (1 << 10)
#define GPMC_AD11_DUPLICATEWAKEUPEVENT          (1 << 11)
#define GPMC_AD12_DUPLICATEWAKEUPEVENT          (1 << 12)
#define GPMC_AD13_DUPLICATEWAKEUPEVENT          (1 << 13)
#define GPMC_AD14_DUPLICATEWAKEUPEVENT          (1 << 14)
#define GPMC_AD15_DUPLICATEWAKEUPEVENT          (1 << 15)
#define GPMC_AD16_DUPLICATEWAKEUPEVENT          (1 << 16)
#define GPMC_AD17_DUPLICATEWAKEUPEVENT          (1 << 17)
#define GPMC_AD18_DUPLICATEWAKEUPEVENT          (1 << 18)
#define GPMC_AD19_DUPLICATEWAKEUPEVENT          (1 << 19)
#define GPMC_AD20_DUPLICATEWAKEUPEVENT          (1 << 20)
#define GPMC_AD21_DUPLICATEWAKEUPEVENT          (1 << 21)
#define GPMC_AD22_DUPLICATEWAKEUPEVENT          (1 << 22)
#define GPMC_AD23_DUPLICATEWAKEUPEVENT          (1 << 23)
#define GPMC_AD24_DUPLICATEWAKEUPEVENT          (1 << 24)
#define GPMC_AD25_DUPLICATEWAKEUPEVENT          (1 << 25)
#define GPMC_NCS0_DUPLICATEWAKEUPEVENT          (1 << 26)
#define GPMC_NCS1_DUPLICATEWAKEUPEVENT          (1 << 27)
#define GPMC_NCS2_DUPLICATEWAKEUPEVENT          (1 << 28)
#define GPMC_NCS3_DUPLICATEWAKEUPEVENT          (1 << 29)
#define GPMC_NWP_DUPLICATEWAKEUPEVENT           (1 << 30)
#define GPMC_CLK_DUPLICATEWAKEUPEVENT           (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_1
#define GPMC_NADV_ALE_DUPLICATEWAKEUPEVENT      (1 << 0)
#define GPMC_NOE_DUPLICATEWAKEUPEVENT           (1 << 1)
#define GPMC_NWE_DUPLICATEWAKEUPEVENT           (1 << 2)
#define GPMC_NBE0_CLE_DUPLICATEWAKEUPEVENT      (1 << 3)
#define GPMC_NBE1_DUPLICATEWAKEUPEVENT          (1 << 4)
#define GPMC_WAIT0_DUPLICATEWAKEUPEVENT         (1 << 5)
#define GPMC_WAIT1_DUPLICATEWAKEUPEVENT         (1 << 6)
#define GPMC_WAIT2_DUPLICATEWAKEUPEVENT         (1 << 7)
#define GPMC_NCS4_DUPLICATEWAKEUPEVENT          (1 << 8)
#define GPMC_NCS5_DUPLICATEWAKEUPEVENT          (1 << 9)
#define GPMC_NCS6_DUPLICATEWAKEUPEVENT          (1 << 10)
#define GPMC_NCS7_DUPLICATEWAKEUPEVENT          (1 << 11)
#define GPIO63_DUPLICATEWAKEUPEVENT             (1 << 12)
#define GPIO64_DUPLICATEWAKEUPEVENT             (1 << 13)
#define GPIO65_DUPLICATEWAKEUPEVENT             (1 << 14)
#define GPIO66_DUPLICATEWAKEUPEVENT             (1 << 15)
#define CSI21_DX0_DUPLICATEWAKEUPEVENT          (1 << 16)
#define CSI21_DY0_DUPLICATEWAKEUPEVENT          (1 << 17)
#define CSI21_DX1_DUPLICATEWAKEUPEVENT          (1 << 18)
#define CSI21_DY1_DUPLICATEWAKEUPEVENT          (1 << 19)
#define CSI21_DX2_DUPLICATEWAKEUPEVENT          (1 << 20)
#define CSI21_DY2_DUPLICATEWAKEUPEVENT          (1 << 21)
#define CSI21_DX3_DUPLICATEWAKEUPEVENT          (1 << 22)
#define CSI21_DY3_DUPLICATEWAKEUPEVENT          (1 << 23)
#define CSI21_DX4_DUPLICATEWAKEUPEVENT          (1 << 24)
#define CSI21_DY4_DUPLICATEWAKEUPEVENT          (1 << 25)
#define CSI22_DX0_DUPLICATEWAKEUPEVENT          (1 << 26)
#define CSI22_DY0_DUPLICATEWAKEUPEVENT          (1 << 27)
#define CSI22_DX1_DUPLICATEWAKEUPEVENT          (1 << 28)
#define CSI22_DY1_DUPLICATEWAKEUPEVENT          (1 << 29)
#define CAM_SHUTTER_DUPLICATEWAKEUPEVENT        (1 << 30)
#define CAM_STROBE_DUPLICATEWAKEUPEVENT         (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_2
#define CAM_GLOBALRESET_DUPLICATEWAKEUPEVENT    (1 << 0)
#define USBB1_ULPITLL_CLK_DUPLICATEWAKEUPEVENT  (1 << 1)
#define USBB1_ULPITLL_STP_DUPLICATEWAKEUPEVENT  (1 << 2)
#define USBB1_ULPITLL_DIR_DUPLICATEWAKEUPEVENT  (1 << 3)
#define USBB1_ULPITLL_NXT_DUPLICATEWAKEUPEVENT  (1 << 4)
#define USBB1_ULPITLL_DAT0_DUPLICATEWAKEUPEVENT (1 << 5)
#define USBB1_ULPITLL_DAT1_DUPLICATEWAKEUPEVENT (1 << 6)
#define USBB1_ULPITLL_DAT2_DUPLICATEWAKEUPEVENT (1 << 7)
#define USBB1_ULPITLL_DAT3_DUPLICATEWAKEUPEVENT (1 << 8)
#define USBB1_ULPITLL_DAT4_DUPLICATEWAKEUPEVENT (1 << 9)
#define USBB1_ULPITLL_DAT5_DUPLICATEWAKEUPEVENT (1 << 10)
#define USBB1_ULPITLL_DAT6_DUPLICATEWAKEUPEVENT (1 << 11)
#define USBB1_ULPITLL_DAT7_DUPLICATEWAKEUPEVENT (1 << 12)
#define USBB1_HSIC_DATA_DUPLICATEWAKEUPEVENT    (1 << 13)
#define USBB1_HSIC_STROBE_DUPLICATEWAKEUPEVENT  (1 << 14)
#define USBC1_ICUSB_DP_DUPLICATEWAKEUPEVENT     (1 << 15)
#define USBC1_ICUSB_DM_DUPLICATEWAKEUPEVENT     (1 << 16)
#define SDMMC1_CLK_DUPLICATEWAKEUPEVENT         (1 << 17)
#define SDMMC1_CMD_DUPLICATEWAKEUPEVENT         (1 << 18)
#define SDMMC1_DAT0_DUPLICATEWAKEUPEVENT        (1 << 19)
#define SDMMC1_DAT1_DUPLICATEWAKEUPEVENT        (1 << 20)
#define SDMMC1_DAT2_DUPLICATEWAKEUPEVENT        (1 << 21)
#define SDMMC1_DAT3_DUPLICATEWAKEUPEVENT        (1 << 22)
#define SDMMC1_DAT4_DUPLICATEWAKEUPEVENT        (1 << 23)
#define SDMMC1_DAT5_DUPLICATEWAKEUPEVENT        (1 << 24)
#define SDMMC1_DAT6_DUPLICATEWAKEUPEVENT        (1 << 25)
#define SDMMC1_DAT7_DUPLICATEWAKEUPEVENT        (1 << 26)
#define ABE_MCBSP2_CLKX_DUPLICATEWAKEUPEVENT    (1 << 27)
#define ABE_MCBSP2_DR_DUPLICATEWAKEUPEVENT      (1 << 28)
#define ABE_MCBSP2_DX_DUPLICATEWAKEUPEVENT      (1 << 29)
#define ABE_MCBSP2_FSX_DUPLICATEWAKEUPEVENT     (1 << 30)
#define ABE_MCBSP1_CLKX_DUPLICATEWAKEUPEVENT    (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_3
#define ABE_MCBSP1_DR_DUPLICATEWAKEUPEVENT      (1 << 0)
#define ABE_MCBSP1_DX_DUPLICATEWAKEUPEVENT      (1 << 1)
#define ABE_MCBSP1_FSX_DUPLICATEWAKEUPEVENT     (1 << 2)
#define ABE_PDM_UL_DATA_DUPLICATEWAKEUPEVENT    (1 << 3)
#define ABE_PDM_DL_DATA_DUPLICATEWAKEUPEVENT    (1 << 4)
#define ABE_PDM_FRAME_DUPLICATEWAKEUPEVENT      (1 << 5)
#define ABE_PDM_LB_CLK_DUPLICATEWAKEUPEVENT     (1 << 6)
#define ABE_CLKS_DUPLICATEWAKEUPEVENT           (1 << 7)
#define ABE_DMIC_CLK1_DUPLICATEWAKEUPEVENT      (1 << 8)
#define ABE_DMIC_DIN1_DUPLICATEWAKEUPEVENT      (1 << 9)
#define ABE_DMIC_DIN2_DUPLICATEWAKEUPEVENT      (1 << 10)
#define ABE_DMIC_DIN3_DUPLICATEWAKEUPEVENT      (1 << 11)
#define UART2_CTS_DUPLICATEWAKEUPEVENT          (1 << 12)
#define UART2_RTS_DUPLICATEWAKEUPEVENT          (1 << 13)
#define UART2_RX_DUPLICATEWAKEUPEVENT           (1 << 14)
#define UART2_TX_DUPLICATEWAKEUPEVENT           (1 << 15)
#define HDQ_SIO_DUPLICATEWAKEUPEVENT            (1 << 16)
#define I2C1_SCL_DUPLICATEWAKEUPEVENT           (1 << 17)
#define I2C1_SDA_DUPLICATEWAKEUPEVENT           (1 << 18)
#define I2C2_SCL_DUPLICATEWAKEUPEVENT           (1 << 19)
#define I2C2_SDA_DUPLICATEWAKEUPEVENT           (1 << 20)
#define I2C3_SCL_DUPLICATEWAKEUPEVENT           (1 << 21)
#define I2C3_SDA_DUPLICATEWAKEUPEVENT           (1 << 22)
#define I2C4_SCL_DUPLICATEWAKEUPEVENT           (1 << 23)
#define I2C4_SDA_DUPLICATEWAKEUPEVENT           (1 << 24)
#define MCSPI1_CLK_DUPLICATEWAKEUPEVENT         (1 << 25)
#define MCSPI1_SOMI_DUPLICATEWAKEUPEVENT        (1 << 26)
#define MCSPI1_SIMO_DUPLICATEWAKEUPEVENT        (1 << 27)
#define MCSPI1_CS0_DUPLICATEWAKEUPEVENT         (1 << 28)
#define MCSPI1_CS1_DUPLICATEWAKEUPEVENT         (1 << 29)
#define MCSPI1_CS2_DUPLICATEWAKEUPEVENT         (1 << 30)
#define MCSPI1_CS3_DUPLICATEWAKEUPEVENT         (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_4
#define UART3_CTS_RCTX_DUPLICATEWAKEUPEVENT     (1 << 0)
#define UART3_RTS_SD_DUPLICATEWAKEUPEVENT       (1 << 1)
#define UART3_RX_IRRX_DUPLICATEWAKEUPEVENT      (1 << 2)
#define UART3_TX_IRTX_DUPLICATEWAKEUPEVENT      (1 << 3)
#define SDMMC5_CLK_DUPLICATEWAKEUPEVENT         (1 << 4)
#define SDMMC5_CMD_DUPLICATEWAKEUPEVENT         (1 << 5)
#define SDMMC5_DAT0_DUPLICATEWAKEUPEVENT        (1 << 6)
#define SDMMC5_DAT1_DUPLICATEWAKEUPEVENT        (1 << 7)
#define SDMMC5_DAT2_DUPLICATEWAKEUPEVENT        (1 << 8)
#define SDMMC5_DAT3_DUPLICATEWAKEUPEVENT        (1 << 9)
#define MCSPI4_CLK_DUPLICATEWAKEUPEVENT         (1 << 10)
#define MCSPI4_SIMO_DUPLICATEWAKEUPEVENT        (1 << 11)
#define MCSPI4_SOMI_DUPLICATEWAKEUPEVENT        (1 << 12)
#define MCSPI4_CS0_DUPLICATEWAKEUPEVENT         (1 << 13)
#define UART4_RX_DUPLICATEWAKEUPEVENT           (1 << 14)
#define UART4_TX_DUPLICATEWAKEUPEVENT           (1 << 15)
#define USBB2_ULPITLL_CLK_DUPLICATEWAKEUPEVENT  (1 << 16)
#define USBB2_ULPITLL_STP_DUPLICATEWAKEUPEVENT  (1 << 17)
#define USBB2_ULPITLL_DIR_DUPLICATEWAKEUPEVENT  (1 << 18)
#define USBB2_ULPITLL_NXT_DUPLICATEWAKEUPEVENT  (1 << 19)
#define USBB2_ULPITLL_DAT0_DUPLICATEWAKEUPEVENT (1 << 20)
#define USBB2_ULPITLL_DAT1_DUPLICATEWAKEUPEVENT (1 << 21)
#define USBB2_ULPITLL_DAT2_DUPLICATEWAKEUPEVENT (1 << 22)
#define USBB2_ULPITLL_DAT3_DUPLICATEWAKEUPEVENT (1 << 23)
#define USBB2_ULPITLL_DAT4_DUPLICATEWAKEUPEVENT (1 << 24)
#define USBB2_ULPITLL_DAT5_DUPLICATEWAKEUPEVENT (1 << 25)
#define USBB2_ULPITLL_DAT6_DUPLICATEWAKEUPEVENT (1 << 26)
#define USBB2_ULPITLL_DAT7_DUPLICATEWAKEUPEVENT (1 << 27)
#define USBB2_HSIC_DATA_DUPLICATEWAKEUPEVENT    (1 << 28)
#define USBB2_HSIC_STROBE_DUPLICATEWAKEUPEVENT  (1 << 29)
#define KPD_COL3_DUPLICATEWAKEUPEVENT           (1 << 30)
#define KPD_COL4_DUPLICATEWAKEUPEVENT           (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_5
#define KPD_COL5_DUPLICATEWAKEUPEVENT           (1 << 0)
#define KPD_COL0_DUPLICATEWAKEUPEVENT           (1 << 1)
#define KPD_COL1_DUPLICATEWAKEUPEVENT           (1 << 2)
#define KPD_COL2_DUPLICATEWAKEUPEVENT           (1 << 3)
#define KPD_ROW3_DUPLICATEWAKEUPEVENT           (1 << 4)
#define KPD_ROW4_DUPLICATEWAKEUPEVENT           (1 << 5)
#define KPD_ROW5_DUPLICATEWAKEUPEVENT           (1 << 6)
#define KPD_ROW0_DUPLICATEWAKEUPEVENT           (1 << 7)
#define KPD_ROW1_DUPLICATEWAKEUPEVENT           (1 << 8)
#define KPD_ROW2_DUPLICATEWAKEUPEVENT           (1 << 9)
#define USBA0_OTG_DP_DUPLICATEWAKEUPEVENT       (1 << 10)
#define FREF_CLK1_OUT_DUPLICATEWAKEUPEVENT      (1 << 11)
#define FREF_CLK2_OUT_DUPLICATEWAKEUPEVENT      (1 << 12)
#define SYS_NIRQ1_DUPLICATEWAKEUPEVENT          (1 << 13)
#define SYS_NIRQ2_DUPLICATEWAKEUPEVENT          (1 << 14)
#define SYS_BOOT0_DUPLICATEWAKEUPEVENT          (1 << 15)
#define SYS_BOOT1_DUPLICATEWAKEUPEVENT          (1 << 16)
#define SYS_BOOT2_DUPLICATEWAKEUPEVENT          (1 << 17)
#define SYS_BOOT3_DUPLICATEWAKEUPEVENT          (1 << 18)
#define SYS_BOOT4_DUPLICATEWAKEUPEVENT          (1 << 19)
#define SYS_BOOT5_DUPLICATEWAKEUPEVENT          (1 << 20)
#define DPM_EMU0_DUPLICATEWAKEUPEVENT           (1 << 21)
#define DPM_EMU1_DUPLICATEWAKEUPEVENT           (1 << 22)
#define DPM_EMU2_DUPLICATEWAKEUPEVENT           (1 << 23)
#define DPM_EMU3_DUPLICATEWAKEUPEVENT           (1 << 24)
#define DPM_EMU4_DUPLICATEWAKEUPEVENT           (1 << 25)
#define DPM_EMU5_DUPLICATEWAKEUPEVENT           (1 << 26)
#define DPM_EMU6_DUPLICATEWAKEUPEVENT           (1 << 27)
#define DPM_EMU7_DUPLICATEWAKEUPEVENT           (1 << 28)
#define DPM_EMU8_DUPLICATEWAKEUPEVENT           (1 << 29)
#define DPM_EMU9_DUPLICATEWAKEUPEVENT           (1 << 30)
#define DPM_EMU10_DUPLICATEWAKEUPEVENT          (1 << 31)

// CONTROL_PADCONF_WAKEUPEVENT_6
#define DPM_EMU11_DUPLICATEWAKEUPEVENT          (1 << 0)
#define DPM_EMU12_DUPLICATEWAKEUPEVENT          (1 << 1)
#define DPM_EMU13_DUPLICATEWAKEUPEVENT          (1 << 2)
#define DPM_EMU14_DUPLICATEWAKEUPEVENT          (1 << 3)
#define DPM_EMU15_DUPLICATEWAKEUPEVENT          (1 << 4)
#define DPM_EMU16_DUPLICATEWAKEUPEVENT          (1 << 5)
#define DPM_EMU17_DUPLICATEWAKEUPEVENT          (1 << 6)
#define DPM_EMU18_DUPLICATEWAKEUPEVENT          (1 << 7)
#define DPM_EMU19_DUPLICATEWAKEUPEVENT          (1 << 8)

// CONTROL_PADCONF_GLOBAL
#define FORCE_OFFMODE_EN                        (1 << 31)

// CONTROL_CORE_PADCONF_MODE
#define VDDS_DV_BANK2_SHARED0                   (1 << 19)
#define VDDS_DV_GPMC1                           (1 << 20)
#define VDDS_DV_BANK7                           (1 << 21)
#define VDDS_DV_SDMMC2                          (1 << 22)
#define VDDS_DV_GPMC0                           (1 << 23)
#define VDDS_DV_CAM                             (1 << 24)
#define VDDS_DV_C2C                             (1 << 25)
#define VDDS_DV_BANK6                           (1 << 26)
#define VDDS_DV_BANK5                           (1 << 27)
#define VDDS_DV_BANK4                           (1 << 28)
#define VDDS_DV_BANK3                           (1 << 29)
#define VDDS_DV_BANK1                           (1 << 30)
#define VDDS_DV_BANK0                           (1 << 31)

// CONTROL_SMART1IO_PADCONF_0
#define UART3_DR1_SC(x)                     (((x) & 0x3) << 4)
#define UART3_DR0_SC(x)                     (((x) & 0x3) << 6)
#define UART1_DR0_SC(x)                     (((x) & 0x3) << 8)
#define MCSPI1_DR0_SC(x)                    (((x) & 0x3) << 10)
#define GPIO_63_64_DR0_SC(x)                (((x) & 0x3) << 12)
#define GPMC_DR3_SC(x)                      (((x) & 0x3) << 16)
#define GPIO_DR9_SC(x)                      (((x) & 0x3) << 20)
#define GPIO_DR8_SC(x)                      (((x) & 0x3) << 22)
#define CAM_DR0_SC(x)                       (((x) & 0x3) << 28)
#define ABE_DR0_SC(x)                       (((x) & 0x3) << 30)

// CONTROL_SMART1IO_PADCONF_1
#define UART3_DR1_LB(x)                     (((x) & 0x3) << 4)
#define UART3_DR0_LB(x)                     (((x) & 0x3) << 6)
#define UART1_DR0_LB(x)                     (((x) & 0x3) << 8)
#define MCSPI1_DR0_LB(x)                    (((x) & 0x3) << 10)
#define GPIO_63_64_DR0_LB(x)                (((x) & 0x3) << 12)
#define GPMC_DR3_LB(x)                      (((x) & 0x3) << 16)
#define GPIO_DR9_LB(x)                      (((x) & 0x3) << 20)
#define GPIO_DR8_LB(x)                      (((x) & 0x3) << 22)
#define CAM_DR0_LB(x)                       (((x) & 0x3) << 28)
#define ABE_DR0_LB(x)                       (((x) & 0x3) << 30)

// CONTROL_SMART3IO_PADCONF_0
#define SPI2_DR0_MB(x)                      (((x) & 0x3) << 0)
#define SDMMC3_DR0_MB(x)                    (((x) & 0x3) << 8)
#define MCSPI4_DR1_MB(x)                    (((x) & 0x3) << 10)
#define MCSPI4_DR0_MB(x)                    (((x) & 0x3) << 12)
#define MCBSP2_DR0_MB(x)                    (((x) & 0x3) << 14)
#define HSI_DR3_MB(x)                       (((x) & 0x3) << 16)
#define HSI_DR2_MB(x)                       (((x) & 0x3) << 18)
#define HSI_DR1_MB(x)                       (((x) & 0x3) << 20)
#define GPIO_DR6_MB(x)                      (((x) & 0x3) << 22)
#define GPIO_DR5_MB(x)                      (((x) & 0x3) << 24)
#define GPIO_DR4_MB(x)                      (((x) & 0x3) << 26)
#define GPIO_DR3_MB(x)                      (((x) & 0x3) << 28)
#define DMIC_DR0_MB(x)                      (((x) & 0x3) << 30)

// CONTROL_SMART3IO_PADCONF_1
#define USBB1_DR2_MB(x)                     (((x) & 0x3) << 0)
#define FREF_DR3_MB(x)                      (((x) & 0x3) << 2)
#define FREF_DR2_MB(x)                      (((x) & 0x3) << 4)
#define PDM_DR0_MB(x)                       (((x) & 0x3) << 6)
#define GPMC_DR1_MB(x)                      (((x) & 0x3) << 12)
#define HSI_DR0_MB(x)                       (((x) & 0x3) << 20)
#define UART4_DR0_MB(x)                     (((x) & 0x3) << 22)
#define UART2_DR1_MB(x)                     (((x) & 0x3) << 24)
#define UART2_DR0_MB(x)                     (((x) & 0x3) << 26)
#define SPI2_DR2_MB(x)                      (((x) & 0x3) << 28)
#define SPI2_DR1_MB(x)                      (((x) & 0x3) << 30)

// CONTROL_SMART3IO_PADCONF_2
#define USBB1_DR2_LB                        (1 << 4)
#define SDMMC3_DR0_LB                       (1 << 5)
#define FREF_DR2_LB                         (1 << 6)
#define PDM_DR0_LB                          (1 << 7)
#define GPMC_DR1_LB                         (1 << 8)
#define FREF_DR3_LB                         (1 << 9)
#define HSI_DR0_LB                          (1 << 10)
#define UART4_DR0_LB                        (1 << 11)
#define UART2_DR1_LB                        (1 << 12)
#define UART2_DR0_LB                        (1 << 13)
#define SPI2_DR2_LB                         (1 << 14)
#define SPI2_DR1_LB                         (1 << 15)
#define SPI2_DR0_LB                         (1 << 16)
#define MCSPI4_DR1_LB                       (1 << 21)
#define MCSPI4_DR0_LB                       (1 << 22)
#define MCBSP2_DR0_LB                       (1 << 23)
#define HSI_DR3_LB                          (1 << 24)
#define HSI_DR2_LB                          (1 << 25)
#define HSI_DR1_LB                          (1 << 26)
#define GPIO_DR6_LB                         (1 << 27)
#define GPIO_DR5_LB                         (1 << 28)
#define GPIO_DR4_LB                         (1 << 29)
#define GPIO_DR3_LB                         (1 << 30)
#define DMIC_DR0_LB                         (1 << 31)

// CONTROL_USBB_HSIC
#define USBB2_HSIC_STROBE_OFFMODE_WD(x)     (((x) & 0x3) << 2)
#define USBB2_HSIC_STROBE_OFFMODE_WD_ENABLE (1 << 4)
#define USBB2_HSIC_DATA_OFFMODE_WD(x)       (((x) & 0x3) << 5)
#define USBB2_HSIC_DATA_OFFMODE_WD_ENABLE   (1 << 7)
#define USBB1_HSIC_STROBE_OFFMODE_WD(x)     (((x) & 0x3) << 8)
#define USBB1_HSIC_STROBE_OFFMODE_WD_ENABLE (1 << 10)
#define USBB1_HSIC_DATA_OFFMODE_WD(x)       (((x) & 0x3) << 11)
#define USBB1_HSIC_DATA_OFFMODE_WD_ENABLE   (1 << 13)
#define USBB2_HSIC_STROBE_WD(x)             (((x) & 0x3) << 14)
#define USBB2_HSIC_DATA_WD(x)               (((x) & 0x3) << 16)
#define USBB1_HSIC_STROBE_WD(x)             (((x) & 0x3) << 18)
#define USBB1_HSIC_DATA_WD(x)               (((x) & 0x3) << 20)
#define USBB1_DR1_I(x)                      (((x) & 0x7) << 22)
#define USBB1_DR1_SR(x)                     (((x) & 0x3) << 25)
#define USBB2_DR1_I(x)                      (((x) & 0x7) << 27)
#define USBB2_DR1_SR(x)                     (((x) & 0x3) << 30)

// CONTROL_SMART3IO_PADCONF_3
#define SLIMBUS2_DR0_LB                     (1 << 14)
#define SLIMBUS1_DR1_LB                     (1 << 15)
#define SLIMBUS2_DR3_LB                     (1 << 16)
#define SLIMBUS2_DR2_LB                     (1 << 17)
#define SLIMBUS2_DR1_LB                     (1 << 18)
#define SLIMBUS1_DR0_LB                     (1 << 19)
#define SLIMBUS2_DR3_MB(x)                  (((x) & 0x3) << 20)
#define SLIMBUS2_DR2_MB(x)                  (((x) & 0x3) << 22)
#define SLIMBUS2_DR1_MB(x)                  (((x) & 0x3) << 24)
#define SLIMBUS2_DR0_MB(x)                  (((x) & 0x3) << 26)
#define SLIMBUS1_DR1_MB(x)                  (((x) & 0x3) << 28)
#define SLIMBUS1_DR0_MB(x)                  (((x) & 0x3) << 30)

// CONTROL_SMART2IO_PADCONF_2
#define USBB1_DR0_DS                        (1 << 11)
#define USBB2_DR0_DS                        (1 << 12)
#define USBA_DR2_DS                         (1 << 13)
#define USBA0_DR1_DS                        (1 << 14)
#define USBA0_DR0_DS                        (1 << 15)
#define UART3_DR5_DS                        (1 << 16)
#define UART3_DR4_DS                        (1 << 17)
#define UART3_DR3_DS                        (1 << 18)
#define UART3_DR2_DS                        (1 << 19)
#define SPI3_DR1_DS                         (1 << 20)
#define SPI3_DR0_DS                         (1 << 21)
#define SDMMC4_DR1_DS                       (1 << 22)
#define SDMMC4_DR0_DS                       (1 << 23)
#define SDMMC3_DR0_DS                       (1 << 24)
#define HSI2_DR2_DS                         (1 << 25)
#define HSI2_DR1_DS                         (1 << 26)
#define HSI2_DR0_DS                         (1 << 27)
#define GPIO_DR10_DS                        (1 << 28)
#define DPM_DR3_DS                          (1 << 29)
#define DPM_DR2_DS                          (1 << 30)
#define DPM_DR1_DS                          (1 << 31)

// CONTROL_SMART1IO_PADCONF_2
#define HDQ_DR0_SC(x)                       (((x) & 0x3) << 22)
#define KPD_DR3_SC(x)                       (((x) & 0x3) << 24)
#define KPD_DR2_SC(x)                       (((x) & 0x3) << 26)
#define KPD_DR1_SC(x)                       (((x) & 0x3) << 28)
#define KPD_DR0_SC(x)                       (((x) & 0x3) << 30)

// CONTROL_SMART1IO_PADCONF_3
#define HDQ_DR0_LB(x)                       (((x) & 0x3) << 22)
#define KPD_DR3_LB(x)                       (((x) & 0x3) << 24)
#define KPD_DR2_LB(x)                       (((x) & 0x3) << 26)
#define KPD_DR1_LB(x)                       (((x) & 0x3) << 28)
#define KPD_DR0_LB(x)                       (((x) & 0x3) << 30)

// CONTROL_C2CIO_PADCONF_0
#define C2C_INT_VREF_AUTO_EN                (1 << 7)
#define C2C_INT_VREF_EN                     (1 << 8)
#define C2C_VREF_CCAP(x)                    (((x) & 0x3) << 9)
#define CMOSEN_C2C_1_FRM_CTRL               (1 << 11)
#define CMOSEN_C2C_0_FRM_CTRL               (1 << 12)
#define SDMMC2_DR0_LB0                      (1 << 13)
#define KPD_DR5_LB0                         (1 << 14)
#define KPD_DR4_LB0                         (1 << 15)
#define GPMC_DR9_LB0                        (1 << 16)
#define GPMC_DR8_LB0                        (1 << 17)
#define GPMC_DR7_LB0                        (1 << 18)
#define GPMC_DR6_LB0                        (1 << 19)
#define GPMC_DR5_LB0                        (1 << 20)
#define GPMC_DR4_LB0                        (1 << 21)
#define GPMC_DR2_LB0                        (1 << 22)
#define GPMC_DR10_LB0                       (1 << 23)
#define GPMC_DR11_LB0                       (1 << 24)
#define GPMC_DR0_LB0                        (1 << 25)
#define GPIO_DR2_LB0                        (1 << 26)
#define GPIO_DR1_LB0                        (1 << 27)
#define GPIO_DR0_LB0                        (1 << 28)
#define C2C_DR2_LB0                         (1 << 29)
#define C2C_DR1_LB0                         (1 << 30)
#define C2C_DR0_LB0                         (1 << 31)

// CONTROL_PBIASLITE
#define USBC1_ICUSB_PWRDNZ                  (1 << 20)
#define MMC1_PBIASLITE_VMODE                (1 << 21)
#define MMC1_PBIASLITE_PWRDNZ               (1 << 22)
#define MMC1_PBIASLITE_VMODE_ERROR          (1 << 23)
#define MMC1_PBIASLITE_SUPPLY_HI_OUT        (1 << 24)
#define MMC1_PBIASLITE_HIZ_MODE             (1 << 25)
#define MMC1_PWRDNZ                         (1 << 26)
#define PBIASLITE1_VMODE                    (1 << 27)
#define PBIASLITE1_PWRDNZ                   (1 << 28)
#define PBIASLITE1_VMODE_ERROR              (1 << 29)
#define PBIASLITE1_SUPPLY_HI_OUT            (1 << 30)
#define PBIASLITE1_HIZ_MODE                 (1 << 31)

// CONTROL_I2C_0
#define I2C1_SCL_PULLUPRESX                 (1 << 0)
#define I2C1_SCL_LOAD_BITS(x)               (((x) & 0x3) << 1)
#define I2C1_SCL_GLFENB                     (1 << 3)
#define I2C2_SCL_PULLUPRESX                 (1 << 4)
#define I2C2_SCL_LOAD_BITS(x)               (((x) & 0x3) << 5)
#define I2C2_SCL_GLFENB                     (1 << 7)
#define I2C3_SCL_PULLUPRESX                 (1 << 8)
#define I2C3_SCL_LOAD_BITS(x)               (((x) & 0x3) << 9)
#define I2C3_SCL_GLFENB                     (1 << 11)
#define I2C4_SCL_PULLUPRESX                 (1 << 12)
#define I2C4_SCL_LOAD_BITS(x)               (((x) & 0x3) << 13)
#define I2C4_SCL_GLFENB                     (1 << 15)
#define I2C1_SDA_PULLUPRESX                 (1 << 16)
#define I2C1_SDA_LOAD_BITS(x)               (((x) & 0x3) << 17)
#define I2C1_SDA_GLFENB                     (1 << 18)
#define I2C2_SDA_PULLUPRESX                 (1 << 19)
#define I2C2_SDA_LOAD_BITS(x)               (((x) & 0x3) << 21)
#define I2C2_SDA_GLFENB                     (1 << 23)
#define I2C3_SDA_PULLUPRESX                 (1 << 24)
#define I2C3_SDA_LOAD_BITS(x)               (((x) & 0x3) << 25)
#define I2C3_SDA_GLFENB                     (1 << 27)
#define I2C4_SDA_PULLUPRESX                 (1 << 28)
#define I2C4_SDA_LOAD_BITS(x)               (((x) & 0x3) << 29)
#define I2C4_SDA_GLFENB                     (1 << 31)

// CONTROL_CAMERA_RX
#define CAMERARX_CSI21_CAMMODE(x)           (((x) & 0x3) << 16)
#define CAMERARX_CSI21_CTRLCLKEN            (1 << 18)
#define CAMERARX_CSI22_CAMMODE(x)           (((x) & 0x3) << 19)
#define CAMERARX_CSI22_CTRLCLKEN            (1 << 21)
#define CAMERARX_CSI21_LANEENABLE0          (1 << 24)
#define CAMERARX_CSI21_LANEENABLE1          (1 << 25)
#define CAMERARX_CSI21_LANEENABLE2          (1 << 26)
#define CAMERARX_CSI21_LANEENABLE3          (1 << 27)
#define CAMERARX_CSI21_LANEENABLE4          (1 << 28)
#define CAMERARX_CSI22_LANEENABLE0          (1 << 29)
#define CAMERARX_CSI22_LANEENABLE1          (1 << 30)

// CONTROL_AVDAC
#define AVDAC_INPUTINV                      (1 << 29)
#define AVDAC_TVOUTBYPASS                   (1 << 30)
#define AVDAC_ACEN                          (1 << 31)

// CONTROL_MMC2
#define MMC2_FEEDBACK_CLK_SEL               (1 << 31)

// CONTROL_DSIPHY
#define DSI2_PIPD(x)                        (((x) & 0x1F) << 14)
#define DSI1_PIPD(x)                        (((x) & 0x1F) << 19)
#define DSI1_LANEENABLE(x)                  (((x) & 0x1F) << 24)
#define DSI2_LANEENABLE(x)                  (((x) & 0x7) << 29)

// CONTROL_MCBSPLP
#define ALBCTRLRX_CLKX                      (1 << 30)
#define ALBCTRLRX_FSX                       (1 << 31)

// CONTROL_USB2PHYCORE
#define USB2PHY_RESETDONETCLK               (1 << 5)
#define USBDPLL_FREQLOCK                    (1 << 6)
#define USB2PHY_DATAPOLARITYN               (1 << 7)
#define USB2PHY_TXBITSTUFFENABLE            (1 << 8)
#define USB2PHY_UTMIRESETDONE               (1 << 9)
#define USB2PHY_MCPCMODEEN                  (1 << 11)
#define USB2PHY_MCPCPUEN                    (1 << 12)
#define USB2PHY_CHGDETECTED                 (1 << 13)
#define USB2PHY_CHGDETDONE                  (1 << 14)
#define USB2PHY_RESTARTCHGDET               (1 << 15)
#define USB2PHY_SRCONDM                     (1 << 16)
#define USB2PHY_SINKONDP                    (1 << 17)
#define USB2PHY_DATADET                     (1 << 18)
#define USB2PHY_CHG_DET_DP_COMP             (1 << 19)
#define USB2PHY_CHG_DET_DM_COMP             (1 << 20)
#define USB2PHY_CHG_DET_STATUS(x)           (((x) & 0x7) << 21)
#define USB2PHY_CHG_ISINK_EN                (1 << 24)
#define USB2PHY_CHG_VSRC_EN                 (1 << 25)
#define USB2PHY_RDP_PU_CHGDET_EN            (1 << 26)
#define USB2PHY_RDM_PD_CHGDET_EN            (1 << 27)
#define USB2PHY_CHG_DET_EXT_CTL             (1 << 28)
#define USB2PHY_GPIOMODE                    (1 << 29)
#define USB2PHY_DISCHGDET                   (1 << 30)
#define USB2PHY_AUTORESUME_EN               (1 << 31)

// CONTROL_I2C_1
#define GPIO65_NMODE                        (1 << 20)
#define GPIO66_NMODE                        (1 << 22)

// CONTROL_MMC1
#define USBC1_ICUSB_DM_PDDIS                (1 << 21)
#define USBC1_ICUSB_DP_PDDIS                (1 << 22)
#define USB_FD_CDEN                         (1 << 23)
#define USBC1_DR0_SPEEDCTRL                 (1 << 24)
#define SDMMC1_DR2_SPEEDCTRL                (1 << 25)
#define SDMMC1_DR1_SPEEDCTRL                (1 << 26)
#define SDMMC1_DR0_SPEEDCTRL                (1 << 27)
#define SDMMC1_PUSTRENGTH_GRP3              (1 << 28)
#define SDMMC1_PUSTRENGTH_GRP2              (1 << 29)
#define SDMMC1_PUSTRENGTH_GRP1              (1 << 30)
#define SDMMC1_PUSTRENGTH_GRP0              (1 << 31)

// CONTROL_HSI
#define HSI2_CALMUX_SEL                     (1 << 28)
#define HSI2_CALLOOP_SEL                    (1 << 29)
#define HSI1_CALMUX_SEL                     (1 << 30)
#define HSI1_CALLOOP_SEL                    (1 << 31)

// CONTROL_USB
#define CARKIT_USBA0_ULPIPHY_DAT1_AUTO_EN   (1 << 30)
#define CARKIT_USBA0_ULPIPHY_DAT0_AUTO_EN   (1 << 31)

// CONTROL_LPDDR2IO1_0
// CONTROL_LPDDR2IO2_0
#define LPDDR2IO_GR1_WD(x)                  (((x) & 0x3) << 1)
#define LPDDR2IO_GR1_I(x)                   (((x) & 0x7) << 3)
#define LPDDR2IO_GR1_SR(x)                  (((x) & 0x3) << 6)
#define LPDDR2IO_GR2_WD(x)                  (((x) & 0x3) << 9)
#define LPDDR2IO_GR2_I(x)                   (((x) & 0x7) << 11)
#define LPDDR2IO_GR2_SR(x)                  (((x) & 0x3) << 14)
#define LPDDR2IO_GR3_WD(x)                  (((x) & 0x3) << 17)
#define LPDDR2IO_GR3_I(x)                   (((x) & 0x7) << 19)
#define LPDDR2IO_GR3_SR(x)                  (((x) & 0x3) << 22)
#define LPDDR2IO_GR4_WD(x)                  (((x) & 0x3) << 25)
#define LPDDR2IO_GR4_I(x)                   (((x) & 0x7) << 27)
#define LPDDR2IO_GR4_SR(x)                  (((x) & 0x3) << 30)

// CONTROL_LPDDR2IO1_1
// CONTROL_LPDDR2IO2_1
#define LPDDR2IO_GR5_WD(x)                  (((x) & 0x3) << 1)
#define LPDDR2IO_GR5_I(x)                   (((x) & 0x7) << 3)
#define LPDDR2IO_GR5_SR(x)                  (((x) & 0x3) << 6)
#define LPDDR2IO_GR6_WD(x)                  (((x) & 0x3) << 9)
#define LPDDR2IO_GR6_I(x)                   (((x) & 0x7) << 11)
#define LPDDR2IO_GR6_SR(x)                  (((x) & 0x3) << 14)
#define LPDDR2IO_GR7_WD(x)                  (((x) & 0x3) << 17)
#define LPDDR2IO_GR7_I(x)                   (((x) & 0x7) << 19)
#define LPDDR2IO_GR7_SR(x)                  (((x) & 0x3) << 22)
#define LPDDR2IO_GR8_WD(x)                  (((x) & 0x3) << 25)
#define LPDDR2IO_GR8_I(x)                   (((x) & 0x7) << 27)
#define LPDDR2IO_GR8_SR(x)                  (((x) & 0x3) << 30)

// CONTROL_LPDDR2IO1_2
// CONTROL_LPDDR2IO2_2
#define LPDDR2IO_GR9_WD(x)                  (((x) & 0x3) << 9)
#define LPDDR2IO_GR9_I(x)                   (((x) & 0x7) << 11)
#define LPDDR2IO_GR9_SR(x)                  (((x) & 0x3) << 14)
#define LPDDR2IO_GR10_WD(x)                 (((x) & 0x3) << 17)
#define LPDDR2IO_GR10_I(x)                  (((x) & 0x7) << 19)
#define LPDDR2IO_GR10_SR(x)                 (((x) & 0x3) << 22)
#define LPDDR2IO_GR11_WD(x)                 (((x) & 0x3) << 25)
#define LPDDR2IO_GR11_I(x)                  (((x) & 0x7) << 27)
#define LPDDR2IO_GR11_SR(x)                 (((x) & 0x3) << 30)

// CONTROL_LPDDR2IO1_3
// CONTROL_LPDDR2IO2_3
#define LPDDR2_INT_VREF_AUTO_EN_DQ          (1 << 0)
#define LPDDR2_INT_VREF_AUTO_EN_CA          (1 << 1)
#define LPDDR2_INT_VREF_EN_DQ               (1 << 2)
#define LPDDR2_INT_VREF_EN_CA               (1 << 3)
#define LPDDR2_VREF_DQ_INT3_TAP1            (1 << 4)
#define LPDDR2_VREF_DQ_INT2_TAP1            (1 << 5)
#define LPDDR2_VREF_DQ_INT3_TAP0            (1 << 6)
#define LPDDR2_VREF_DQ_INT2_TAP0            (1 << 7)
#define LPDDR2_VREF_DQ_INT3_CCAP1           (1 << 8)
#define LPDDR2_VREF_DQ_INT2_CCAP1           (1 << 9)
#define LPDDR2_VREF_DQ_INT3_CCAP0           (1 << 10)
#define LPDDR2_VREF_DQ_INT2_CCAP0           (1 << 11)
#define LPDDR2_VREF_DQ_TAP1                 (1 << 12)
#define LPDDR2_VREF_DQ_TAP0                 (1 << 13)
#define LPDDR2_VREF_DQ_CCAP1                (1 << 14)
#define LPDDR2_VREF_DQ_CCAP0                (1 << 15)
#define LPDDR2_VREF_DQ_INT1_TAP1            (1 << 16)
#define LPDDR2_VREF_DQ_INT1_TAP0            (1 << 17)
#define LPDDR2_VREF_DQ_INT1_CCAP1           (1 << 18)
#define LPDDR2_VREF_DQ_INT1_CCAP0           (1 << 19)
#define LPDDR2_VREF_DQ_INT0_TAP1            (1 << 20)
#define LPDDR2_VREF_DQ_INT0_TAP0            (1 << 21)
#define LPDDR2_VREF_DQ_INT0_CCAP1           (1 << 22)
#define LPDDR2_VREF_DQ_INT0_CCAP0           (1 << 23)
#define LPDDR2_VREF_CA_TAP1                 (1 << 24)
#define LPDDR2_VREF_CA_TAP0                 (1 << 25)
#define LPDDR2_VREF_CA_INT_TAP1             (1 << 26)
#define LPDDR2_VREF_CA_INT_TAP0             (1 << 27)
#define LPDDR2_VREF_CA_INT_CCAP1            (1 << 28)
#define LPDDR2_VREF_CA_INT_CCAP0            (1 << 29)
#define LPDDR2_VREF_CA_CCAP1                (1 << 30)
#define LPDDR2_VREF_CA_CCAP0                (1 << 31)

// CONTROL_CORE_CONTROL_SPARE_R_C0
#define CORE_CONTROL_SPARE_R_C7             (1 << 24)
#define CORE_CONTROL_SPARE_R_C6             (1 << 25)
#define CORE_CONTROL_SPARE_R_C5             (1 << 26)
#define CORE_CONTROL_SPARE_R_C4             (1 << 27)
#define CORE_CONTROL_SPARE_R_C3             (1 << 28)
#define CORE_CONTROL_SPARE_R_C2             (1 << 29)
#define CORE_CONTROL_SPARE_R_C1             (1 << 30)
#define CORE_CONTROL_SPARE_R_C0             (1 << 31)

// CONTROL_EFUSE_1
#define AVDAC_TRIM_BYTE0(x)                 ((x) & 0xFF)
#define AVDAC_TRIM_BYTE1(x)                 (((x) & 0xFF) << 8)
#define AVDAC_TRIM_BYTE2(x)                 (((x) & 0xFF) << 16)
#define AVDAC_TRIM_BYTE3(x)                 (((x) & 0x7F) << 24)

// CONTROL_EFUSE_2
#define LPDDR2_PTV_P5                       (1 << 14)
#define LPDDR2_PTV_P4                       (1 << 15)
#define LPDDR2_PTV_P3                       (1 << 16)
#define LPDDR2_PTV_P2                       (1 << 17)
#define LPDDR2_PTV_P1                       (1 << 18)
#define LPDDR2_PTV_N5                       (1 << 19)
#define LPDDR2_PTV_N4                       (1 << 20)
#define LPDDR2_PTV_N3                       (1 << 21)
#define LPDDR2_PTV_N2                       (1 << 22)
#define LPDDR2_PTV_N1                       (1 << 23)
#define EFUSE_SMART2TEST_N3                 (1 << 24)
#define EFUSE_SMART2TEST_N2                 (1 << 25)
#define EFUSE_SMART2TEST_N1                 (1 << 26)
#define EFUSE_SMART2TEST_N0                 (1 << 27)
#define EFUSE_SMART2TEST_P3                 (1 << 28)
#define EFUSE_SMART2TEST_P2                 (1 << 29)
#define EFUSE_SMART2TEST_P1                 (1 << 30)
#define EFUSE_SMART2TEST_P0                 (1 << 31)

// CONTROL_EFUSE_3
#define STD_FUSE_SPARE_4(x)                 ((x) & 0xFF)
#define STD_FUSE_SPARE_3(x)                 (((x) & 0xFF) << 8)
#define STD_FUSE_SPARE_2(x)                 (((x) & 0xFF) << 16)
#define STD_FUSE_SPARE_1(x)                 (((x) & 0xFF) << 24)

// CONTROL_EFUSE_4
#define STD_FUSE_SPARE_8(x)                 ((x) & 0xFF)
#define STD_FUSE_SPARE_7(x)                 (((x) & 0xFF) << 8)
#define STD_FUSE_SPARE_6(x)                 (((x) & 0xFF) << 16)
#define STD_FUSE_SPARE_5(x)                 (((x) & 0xFF) << 24)

// CONTROL_WKUP_PADCONF_WAKEUPEVENT_0
#define GPIO_WK0_DUPLICATEWAKEUPEVENT               (1 << 0)
#define GPIO_WK1_DUPLICATEWAKEUPEVENT               (1 << 1)
#define GPIO_WK2_DUPLICATEWAKEUPEVENT               (1 << 2)
#define GPIO_WK3_DUPLICATEWAKEUPEVENT               (1 << 3)
#define GPIO_WK4_DUPLICATEWAKEUPEVENT               (1 << 4)
#define SR_SCL_DUPLICATEWAKEUPEVENT                 (1 << 5)
#define SR_SDA_DUPLICATEWAKEUPEVENT                 (1 << 6)
#define FREF_CLK_IOREQ_DUPLICATEWAKEUPEVENT         (1 << 7)
#define FREF_CLK0_OUT_DUPLICATEWAKEUPEVENT          (1 << 8)
#define FREF_CLK3_REQ_DUPLICATEWAKEUPEVENT          (1 << 9)
#define FREF_CLK3_OUT_DUPLICATEWAKEUPEVENT          (1 << 10)
#define FREF_CLK4_REQ_DUPLICATEWAKEUPEVENT          (1 << 11)
#define FREF_CLK4_OUT_DUPLICATEWAKEUPEVENT          (1 << 12)
#define SYS_32K_DUPLICATEWAKEUPEVENT                (1 << 13)
#define SYS_NRESWARM_DUPLICATEWAKEUPEVENT           (1 << 14)
#define SYS_PWR_REQ_DUPLICATEWAKEUPEVENT            (1 << 15)
#define SYS_PWRON_RESET_OUT_DUPLICATEWAKEUPEVENT    (1 << 16)
#define SYS_BOOT6_DUPLICATEWAKEUPEVENT              (1 << 17)
#define SYS_BOOT7_DUPLICATEWAKEUPEVENT              (1 << 18)
#define JTAG_NTRST_DUPLICATEWAKEUPEVENT             (1 << 19)
#define JTAG_TCK_DUPLICATEWAKEUPEVENT               (1 << 20)
#define JTAG_RTCK_DUPLICATEWAKEUPEVENT              (1 << 21)
#define JTAG_TMS_TMSC_DUPLICATEWAKEUPEVENT          (1 << 22)
#define JTAG_TDI_DUPLICATEWAKEUPEVENT               (1 << 23)
#define JTAG_TDO_DUPLICATEWAKEUPEVENT               (1 << 24)

// CONTROL_SMART1NOPMIO_PADCONF_0
#define GPIOWK4_DR0_SC(x)                   (((x) & 0x3) << 12)
#define DPM_DR0_SC(x)                       (((x) & 0x3) << 14)
#define GPIO_DR7_SC(x)                      (((x) & 0x3) << 18)
#define FREF_DR0_SC(x)                      (((x) & 0x3) << 30)

// CONTROL_SMART1NOPMIO_PADCONF_1
#define GPIOWK4_DR0_LB(x)                   (((x) & 0x3) << 12)
#define DPM_DR0_LB(x)                       (((x) & 0x3) << 14)
#define GPIO_DR7_LB(x)                      (((x) & 0x3) << 18)
#define FREF_DR0_LB(x)                      (((x) & 0x3) << 30)

// CONTROL_WKUP_PADCONF_MODE
#define VDDS_DV_BANK2_SHARED1               (1 << 30)
#define VDDS_DV_FREF                        (1 << 31)

// CONTROL_XTAL_OSCILLATOR
#define OSCILLATOR_OS_OUT                   (1 << 30)
#define OSCILLATOR_BOOST                    (1 << 31)

// CONTROL_SMART3NOPMIO_PADCONF_0
#define FREF_DR4_MB(x)                      (((x) & 0x3) << 22)
#define FREF_DR7_MB(x)                      (((x) & 0x3) << 24)
#define FREF_DR6_MB(x)                      (((x) & 0x3) << 26)
#define FREF_DR5_MB(x)                      (((x) & 0x3) << 28)
#define FREF_DR1_MB(x)                      (((x) & 0x3) << 30)

// CONTROL_SMART3NOPMIO_PADCONF_1
#define FREF_DR4_LB(x)                      (((x) & 0x3) << 22)
#define FREF_DR7_LB(x)                      (((x) & 0x3) << 24)
#define FREF_DR6_LB(x)                      (((x) & 0x3) << 26)
#define FREF_DR5_LB(x)                      (((x) & 0x3) << 28)
#define FREF_DR1_LB(x)                      (((x) & 0x3) << 30)

// CONTROL_GPIOWK
#define GPIOWK_IO_PWRDNZ                    (1 << 28)
#define PAD_GPIO_WK2_LOW                    (1 << 29)
#define PAD_GPIO_WK1_LOW                    (1 << 31)

// CONTROL_I2C_2
#define SR_SCL_PULLUPRESX                   (1 << 24)
#define SR_SCL_LOAD_BITS(x)                 (((x) & 0x3) << 25)
#define SR_SCL_GLFENB                       (1 << 27)
#define SR_SDA_PULLUPRESX                   (1 << 28)
#define SR_SDA_LOAD_BITS(x)                 (((x) & 0x3) << 29)
#define SR_SDA_GLFENB                       (1 << 30)

// CONTROL_JTAG
#define JTAG_TDO_EN                         (1 << 27)
#define JTAG_TDI_EN                         (1 << 28)
#define JTAG_RTCK_EN                        (1 << 29)
#define JTAG_TCK_EN                         (1 << 30)
#define JTAG_NTRST_EN                       (1 << 31)

// CONTROL_SYS
#define SYS_NRESWARM_PIPU                   (1 << 31)

// CONTROL_WKUP_CONTROL_SPARE_R_C0
#define WKUP_CONTROL_SPARE_R_C7             (1 << 24)
#define WKUP_CONTROL_SPARE_R_C6             (1 << 25)
#define WKUP_CONTROL_SPARE_R_C5             (1 << 26)
#define WKUP_CONTROL_SPARE_R_C4             (1 << 27)
#define WKUP_CONTROL_SPARE_R_C3             (1 << 28)
#define WKUP_CONTROL_SPARE_R_C2             (1 << 29)
#define WKUP_CONTROL_SPARE_R_C1             (1 << 30)
#define WKUP_CONTROL_SPARE_R_C0             (1 << 31)

