/* uOS interrupt handlers for ATmega161.
 * This file was generated by script 'mkintr.py' from data 'interrupt.cfg'.
 * Do not edit it manually! */

	HANDLE (0, clearb_r30 (6, GIMSK))
	HANDLE (1, clearb_r30 (7, GIMSK))
	HANDLE (2, clearb_r30 (5, GIMSK))
	HANDLE (3, clearb_r30 (7, TIMSK))
	HANDLE (4, clearb_r30 (6, TIMSK))
	HANDLE (5, clearb_r30 (5, TIMSK))
	HANDLE (6, clearb_r30 (4, TIMSK))
	HANDLE (7, clearb_r30 (3, TIMSK))
	HANDLE (8, clearb_r30 (2, TIMSK))
	HANDLE (9, clearb_r30 (1, TIMSK))
	HANDLE (10, clearb_r30 (0, TIMSK))
	HANDLE (11, clearb_r30 (SPIE, SPCR))
	HANDLE (12, clearb_r30 (RXCIE, UCR))
	HANDLE (13, clearb_r30 (RXCIE, UCSR1B))
	HANDLE (14, clearb_r30 (UDRIE, UCR))
	HANDLE (15, clearb_r30 (UDRIE, UCSR1B))
	HANDLE (16, clearb_r30 (TXCIE, UCR))
	HANDLE (17, clearb_r30 (TXCIE, UCSR1B))
	HANDLE (18, clearb_r30 (EERIE, EECR))
	HANDLE (19, clearb_r30 (ACIE, ACSR))

void arch_intr_allow (int irq)
{
	switch ((unsigned char) irq) {
	case 0: setb (6, GIMSK); break;
	case 1: setb (7, GIMSK); break;
	case 2: setb (5, GIMSK); break;
	case 3: setb (7, TIMSK); break;
	case 4: setb (6, TIMSK); break;
	case 5: setb (5, TIMSK); break;
	case 6: setb (4, TIMSK); break;
	case 7: setb (3, TIMSK); break;
	case 8: setb (2, TIMSK); break;
	case 9: setb (1, TIMSK); break;
	case 10: setb (0, TIMSK); break;
	case 11: setb (SPIE, SPCR); break;
	case 12: setb (RXCIE, UCR); break;
	case 13: setb (RXCIE, UCSR1B); break;
	case 14: break;
	case 15: break;
	case 16: setb (TXCIE, UCR); break;
	case 17: setb (TXCIE, UCSR1B); break;
	case 18: setb (EERIE, EECR); break;
	case 19: setb (ACIE, ACSR); break;
	}
}
