/* uOS interrupt handlers for ATmega168.
 * This file was generated by script 'mkintr.py' from data 'interrupt.cfg'.
 * Do not edit it manually! */

	HANDLE (0, clearb_r30 (0, EIMSK))
	HANDLE (1, clearb_r30 (1, EIMSK))
	HANDLE (2, clearb_r30 (PCIE0, PCICR))
	HANDLE (3, clearb_r30 (PCIE1, PCICR))
	HANDLE (4, clearb_r30 (PCIE2, PCICR))
	HANDLE (5, clearb_r30 (WDIE, WDTCSR))
	HANDLE (6, clearb_r30 (OCIE2A, TIMSK2))
	HANDLE (7, clearb_r30 (OCIE2B, TIMSK2))
	HANDLE (8, clearb_r30 (TOIE2, TIMSK2))
	HANDLE (9, clearb_r30 (ICIE1, TIMSK1))
	HANDLE (10, clearb_r30 (OCIE1A, TIMSK1))
	HANDLE (11, clearb_r30 (OCIE1B, TIMSK1))
	HANDLE (12, clearb_r30 (TOIE1, TIMSK1))
	HANDLE (13, clearb_r30 (OCIE0A, TIMSK0))
	HANDLE (14, clearb_r30 (OCIE0B, TIMSK0))
	HANDLE (15, clearb_r30 (TOIE0, TIMSK0))
	HANDLE (16, clearb_r30 (SPIE, SPCR))
	HANDLE (17, clearb_r30 (RXCIE, UCR))
	HANDLE (18, clearb_r30 (UDRIE, UCR))
	HANDLE (19, clearb_r30 (TXCIE, UCR))
	HANDLE (20, clearb_r30 (ADIE, ADCSRA))
	HANDLE (21, clearb_r30 (EERIE, EECR))
	HANDLE (22, clearb_r30 (ACIE, ACSR))
	HANDLE (23, clearb_r30 (TWIE, TWCR))
	HANDLE (24, clearb_r30 (SPMIE, SPMCSR))

void arch_intr_allow (int irq)
{
	switch ((unsigned char) irq) {
	case 0: setb (0, EIMSK); break;
	case 1: setb (1, EIMSK); break;
	case 2: setb (PCIE0, PCICR); break;
	case 3: setb (PCIE1, PCICR); break;
	case 4: setb (PCIE2, PCICR); break;
	case 5: setb (WDIE, WDTCSR); break;
	case 6: setb (OCIE2A, TIMSK2); break;
	case 7: setb (OCIE2B, TIMSK2); break;
	case 8: setb (TOIE2, TIMSK2); break;
	case 9: setb (ICIE1, TIMSK1); break;
	case 10: setb (OCIE1A, TIMSK1); break;
	case 11: setb (OCIE1B, TIMSK1); break;
	case 12: setb (TOIE1, TIMSK1); break;
	case 13: setb (OCIE0A, TIMSK0); break;
	case 14: setb (OCIE0B, TIMSK0); break;
	case 15: setb (TOIE0, TIMSK0); break;
	case 16: setb (SPIE, SPCR); break;
	case 17: setb (RXCIE, UCR); break;
	case 18: break;
	case 19: setb (TXCIE, UCR); break;
	case 20: setb (ADIE, ADCSRA); break;
	case 21: setb (EERIE, EECR); break;
	case 22: setb (ACIE, ACSR); break;
	case 23: setb (TWIE, TWCR); break;
	case 24: setb (SPMIE, SPMCSR); break;
	}
}
